project:
  type: book

book:
  title: "ACT2003 — Recueil d'exercices"
  author: "Marie-Pier Côté"
  language: fr
  chapters:
    - index.qmd
    - part: "Exercices"
      chapters:
        - chapitres/simple.qmd
        - chapitres/multiple.qmd
        - chapitres/selection.qmd
        - chapitres/glm.qmd

  search: true
  sidebar:
    style: docked

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            macros: {
              esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
              Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
              ex:     "\\mathbb{E}",
              var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
              Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
              vr:     "\\mathrm{Var}",
              prob:   "\\Pr",
              Prob:   "\\Pr",
              cov:    ["\\mathrm{Cov}\\!\\left(#1\\right)",1],
              Cov:    "\\mathrm{Cov}",
              SST:    "\\mathrm{SST}",
              SSR:    "\\mathrm{SSR}",
              SSE:    "\\mathrm{SSE}",
              MSE:    "\\mathrm{MSE}",
              MSR:    "\\mathrm{MSR}",
              d:      "\\mathrm{d}",
              bm:     ["\\boldsymbol{#1}", 1],
              yvec:   "\\mathbf{Y}",
              xvec:   "\\mathbf{x}",
              Xmat:   "\\mathbf{X}",
              betavec: "\\boldsymbol{\\beta}",
              epsvec: "\\boldsymbol{\\varepsilon}",
              mat:    ["\\mathbf{#1}", 1],
              varmat:    ["\\mathbf{V} ( #1 )", 1],
              hatbetavec: "\\boldsymbol{\\hat{\\beta}}",
              hatepsvec: "\\boldsymbol{\\hat{\\varepsilon}}",
              Norm: "\\mathcal{N}",
              diag: "\\mathrm{diag}"
            }
          }
        };
        </script>

lang: fr

