project:
  type: book

book:
  title: "ACT2000 — Recueil d'exercices"
  author: "Marie-Pier Côté"
  language: fr
  chapters:
    - index.qmd
    - part: "Exercices"
      chapters:
        - chapitres//binom.qmd
        - chapitres//comptage.qmd
        - chapitres//glm.qmd
        - chapitres//multiple.qmd
        - chapitres//selection.qmd
        - chapitres//simple.qmd
  search: true
  sidebar:
    style: docked

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            macros: {
              esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
              Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
              ex:     "\\mathbb{E}",
              var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
              Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
              vr:     "\\mathrm{Var}",
              prob:   "\\Pr",
              Prob:   "\\Pr",
              Cov:    "\\mathrm{Cov}",
              d:      "\\mathrm{d}",
              bm:     ["\\boldsymbol{#1}", 1]
            }
          }
        };
        </script>

lang: fr

