## Décès dus au cancer du poumon {#sec-comptage-deces_cancer_poumon}

Le fichier de données \texttt{MNLung.csv} (séparé avec des virgules) contient des données sur le nombre de décès dus au cancer du poumon dans 87 régions au Minnesota, pour les hommes et les femmes. L'objectif de l'étude pour laquelle les données ont été recueillies était d'examiner si l'exposition au gaz radon est relié à un changement dans le taux de morbidité standardisé. La base de données contient sept colonnes:
\begin{description}
\item[County:] Nom de la région;
\item[ID:] Numéro d'identifcation de la région dans la base de données;
\item[YM:] Nombre de décès dûs au cancer du poumon chez les hommes sur une période de 5 ans;
\item[EM:] Espérance du nombre de cas YM, basé sur des facteurs démographiques;
\item[YF:] Nombre de décès dûs au cancer du poumon chez les femmes sur une période de 5 ans;
\item[EF:] Espérance du nombre de cas YF, basé sur des facteurs démographiques;
\item[Radon:] Mesure moyenne de l'exposition au radon dans chaque région pour la période de 5 ans.
\end{description}
Le taux de morbidité standardisé (SMR) pour la région $i$ est défini comme $$SMR_i=\frac{Y_i}{E_i}.$$ En utilisant un modèle linéaire généralisé Poisson approprié, répondre aux question suivantes:

**a)** Y a-t-il des preuves dans ces données que le radon est associé avec un changement dans le SMR ?

**b)** Y a-t-il une différence entre le SMR pour les hommes et les femmes, lorsque l'on inclut ou pas la variable explicative radon dans le modèle?

**c)** Donner les prévisions pour le SMR, avec la mesure d'incertitude, pour des hommes dans une région hypothétique où l'exposition moyenne au radon est de 6 unités.

**d)** Commenter sur la validité du modèle de Poisson pour ces données.

::: {.callout-tip collapse="true" title="Solution complète"}
```{r echo}
#| echo: false

dat <- read.csv("data/MNlung.csv")
attach(dat)
```

**a)** If $Y_{i}\sim Poisson(E_{i}\lambda_{i})$, then, using the canonical link, $$\log(\mu_{i})=log(E_{i})+log(\lambda_{i}),$$ where $\lambda_{i}$ is the mean $SMR$ for observation $i$. $\log(E_{i})$, the natural logarithm of the expected count of lung cancer based on the demographics of the county, is passed to the \texttt{glm} function as an offset factor. The data for males and females are concatenated to create a model with one covariate, Radon exposure, and one factor predictor, Sex, which takes 2 levels (0 for males and 1 for females). ```{r} Ytot <- c(YM,YF) Etot <- c(EM,EF) Sex <- c(rep(0,length(YM)),rep(1,length(YF))) ## 1 if female Radontot <- rep(Radon,2) modsex <- glm(Ytot Sex+offset(log(Etot)),family=poisson) modsexrad <- glm(Ytot Radontot+Sex+offset(log(Etot)),family=poisson) anova(modsex,modsexrad) qchisq(0.99,1) ``` As shown above, the analysis of deviance shows strong evidence that the radon exposure influences the number of lung cancer in a particular county: $$
\begin{aligned} \Delta Deviance = 46.22 > \chi^{2}_{(1;0.99)}=6.6349. \end{aligned}
$$

**b)** The null model and the model including sex only are fitted. ```{r} modtot <- glm(Ytot 1+offset(log(Etot)),family=poisson) modsex <- glm(Ytot Sex+offset(log(Etot)),family=poisson) anova(modtot,modsex) qchisq(0.95,1) ``` The analysis of deviance shows that $\Delta Deviance= 0.0093398<\chi^{2}_{(1;0.95)}=3.8415$. Hence, the null model is an appropriate simplification of the model including the factor Sex, so the factor is not significant. However, below is the \texttt{R} output for the analysis of deviance when the covariate Radon (known to be significant from a) is included in the model. If we first consider the model with main effects and interactions, we see that $\Delta Deviance= 8.823>\chi^{2}_{(1;0.99)}$, meaning that the model with main effects only is not an adequate simplification of the model with main effects and interactions. Thus, the factor predictor Sex is significant in the model through its interaction with the covariate Radon. Note that even if the main effect of the Sex does not appear to be significant, it is kept in the model by convention. ```{r} modtotrad <- glm(Ytot Radontot+offset(log(Etot)),family=poisson) modsexrad <- glm(Ytot Radontot+Sex+offset(log(Etot)),family=poisson) modsexradINT <- glm(Ytot Radontot*Sex+offset(log(Etot)),family=poisson) anova(modtot,modtotrad,modsexrad,modsexradINT) ```

**c)** The predictions are obtained using the command ```{r echo} #| eval: false predict(modsexradINT,data.frame(Radontot=6,Sex=0,Etot=1),type="response",se.fit=TRUE) ``` If the model Sex*Radon is used, we find $$\hat{SMR}_{Sex=0,Radon=6}=0.9708183,$$ with a standard error of 0.01415307.

**d)** The model Sex*Radon has a deviance of 355.23 on 170 degrees of freedom. A heuristic check for the validity of the model is to calculate the estimated dispersion parameter $$\hat{\phi}=\frac{355.23}{170}=2.089$$ and to compare it with 1, the dispersion parameter implied in the Poisson model. This check suggests the presence of overdispersion in the data as $\hat{\phi}$ is greater than 1. Fitting the quasipoisson model also leads to the same conclusion: the estimated dispersion parameter is 1.98311, closer to 2. Thus, we can conclude that the Poisson model is not adequate, we might consider fitting a Negative Binomial model to capture the overdispersion.
:::

