<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Modélisation de données binomiales – ACT2003 — Recueil d'exercices</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapitres/comptage.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a522afb83bf8ae494942cf1b0ac9d4c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    macros: {
      esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      ex:     "\\mathbb{E}",
      var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      vr:     "\\mathrm{Var}",
      prob:   "\\Pr",
      Prob:   "\\Pr",
      cov:    ["\\mathrm{Cov}\\!\\left(#1\\right)",1],
      Cov:    "\\mathrm{Cov}",
      SST:    "\\mathrm{SST}",
      SSR:    "\\mathrm{SSR}",
      SSE:    "\\mathrm{SSE}",
      MSE:    "\\mathrm{MSE}",
      MSR:    "\\mathrm{MSR}",
      d:      "\\mathrm{d}",
      bm:     ["\\boldsymbol{#1}", 1],
      yvec:   "\\mathbf{Y}",
      xvec:   "\\mathbf{x}",
      Xmat:   "\\mathbf{X}",
      betavec: "\\boldsymbol{\\beta}",
      epsvec: "\\boldsymbol{\\varepsilon}",
      mat:    ["\\mathbf{#1}", 1],
      varmat:    ["\\mathbf{V} ( #1 )", 1],
      hatbetavec: "\\boldsymbol{\\hat{\\beta}}",
      hatepsvec: "\\boldsymbol{\\hat{\\varepsilon}}",
      Norm: "\\mathcal{N}",
      diag: "\\mathrm{diag}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/binom.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACT2003 — Recueil d’exercices</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Régression linéaire simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Régression linéaire multiple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sélection de modèle et régression régularisée</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/comptage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/binom.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sec-binom-contributions_etoiles_nba" id="toc-sec-binom-contributions_etoiles_nba" class="nav-link active" data-scroll-target="#sec-binom-contributions_etoiles_nba"><span class="header-section-number">7.1</span> Contribution des joueurs étoiles de la NBA</a></li>
  <li><a href="#sec-binom-groupement_binomiales" id="toc-sec-binom-groupement_binomiales" class="nav-link" data-scroll-target="#sec-binom-groupement_binomiales"><span class="header-section-number">7.2</span> Groupement de données binomiales</a></li>
  <li><a href="#sec-binom-age_kyphosis" id="toc-sec-binom-age_kyphosis" class="nav-link" data-scroll-target="#sec-binom-age_kyphosis"><span class="header-section-number">7.3</span> Effet de l’âge sur la kyphosis</a></li>
  <li><a href="#sec-binom-cancer_peau_st_paul" id="toc-sec-binom-cancer_peau_st_paul" class="nav-link" data-scroll-target="#sec-binom-cancer_peau_st_paul"><span class="header-section-number">7.4</span> Cas de cancer de la peau parmi des femmes à St-Paul</a></li>
  <li><a href="#sec-binom-pearson_statistique" id="toc-sec-binom-pearson_statistique" class="nav-link" data-scroll-target="#sec-binom-pearson_statistique"><span class="header-section-number">7.5</span> Statistique de Pearson pour le modèle binomial</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/binom.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="sec-binom-contributions_etoiles_nba" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-binom-contributions_etoiles_nba"><span class="header-section-number">7.1</span> Contribution des joueurs étoiles de la NBA</h2>
<p>Jones &amp; Parker (2010) ont écrit un article sur les contributions des joueurs étoiles de la NBA. Entre autres, ils ont donné des équations de prévision pour la probabilité <span class="math inline">\(\pi\)</span> de victoire pour un match de LeBron James dans la saison 2008-2009. Les variables exogènes sont :</p>
<ul>
<li><p><span class="math inline">\(x_1\)</span> : Points produits par centaine de possessions (note offensive).</p></li>
<li><p><span class="math inline">\(x_2\)</span> : Points donnés par centaine de possessions (note défensive), plus petit signifie “meilleur” dans ce cas.</p></li>
<li><p><span class="math inline">\(x_3\)</span> : Vaut 1 si la partie est discutée à domicile (0 sinon).</p></li>
</ul>
<p>Les coefficients estimés sont</p>
<p><span class="math display">\[
\hat{\beta}_0=1.379, \quad ~ \hat{\beta}_1=0.119,\quad ~ \hat{\beta}_2=-0.139,\quad \text{ et}\quad ~ \hat{\beta}_3=3.393.
\]</span></p>
<p><strong>a)</strong> On a utilisé un lien logistique. Écrire l’équation de la probabilité estimée <span class="math inline">\(\hat{\pi}\)</span> en fonction des paramètres du modèle.</p>
<p><strong>b)</strong> Calculer la probabilité de gain lorsque la note défensive de LeBron James est égale à sa médiane pour la saison, i.e., <span class="math inline">\(x_2=99.5\)</span>, que la note offensive est à son <span class="math inline">\(75^{e}\)</span> centile, <span class="math inline">\(x_1=136.1\)</span> et que <span class="math inline">\(x_3=0\)</span>. Refaire avec le <span class="math inline">\(25^e\)</span> centile <span class="math inline">\(x_1=108.7\)</span>, comparer et interpréter.</p>
<p><strong>c)</strong> Quel est l’impact de la variable <span class="math inline">\(x_3\)</span>? Utiliser les médianes <span class="math inline">\(x_1=123.2\)</span> et <span class="math inline">\(x_2=99.5\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong><br>
<span class="math display">\[
\mathrm{logit}(\hat{\pi})=1.379+0.119x_1-0.139x_2+3.393x_3 \Rightarrow \hat{\pi}=\frac{\exp(1.379+0.119x_1-0.139x_2+3.393x_3)}{1+\exp(1.379+0.119x_1-0.139x_2+3.393x_3)}
\]</span></p>
<p><strong>b)</strong> Au <span class="math inline">\(75^e\)</span> centile, on a</p>
<p><span class="math display">\[
\hat{\pi}=\frac{\exp(1.379+0.119\times 136.1-0.139\times 99.5)}{1+\exp(1.379+0.119\times 136.1-0.139\times 99.5)}=97.68\%.
\]</span></p>
<p>Puis, au <span class="math inline">\(25^e\)</span> centile,</p>
<p><span class="math display">\[
\hat{\pi}=\frac{\exp(1.379+0.119\times 108.7-0.139\times 99.5)}{1+\exp(1.379+0.119\times 108.7-0.139\times 99.5)}=61.86\%.
\]</span></p>
<p>Cela signifie que la probabilité de gain augmente beaucoup lorsque LeBron James est en forme.</p>
<p><strong>c)</strong></p>
<p>À l’étranger, on a <span class="math display">\[
\hat{\pi}=\frac{\exp(1.379+0.119\times 123.2-0.139\times 99.5)}{1+\exp(1.379+0.119\times 123.2-0.139\times 99.5)}=90.1\%.
\]</span></p>
<p>À domicile, on a <span class="math display">\[
\hat{\pi}=\frac{\exp(1.379+0.119\times 123.2-0.139\times 99.5+3.393)}{1+\exp(1.379+0.119\times 123.2-0.139\times 99.5+3.393)}=99.6\%.
\]</span> L’effet de disputer le match à domicile est donc un augmentation de 10.5 % de la probabilité de gain lorsque les notes offensive et défensive de LeBron James sont égales à leur médiane.</p>
</div>
</div>
</div>
</section>
<section id="sec-binom-groupement_binomiales" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-binom-groupement_binomiales"><span class="header-section-number">7.2</span> Groupement de données binomiales</h2>
<p>Il y a plusieurs moyens de représenter des données binomiales. Elles peuvent être groupées ou non, puisqu’une somme de <span class="math inline">\(m\)</span> variables aléatoires Bernoulli<span class="math inline">\((\pi)\)</span> est distribuée comme une variable aléatoire Binomiale<span class="math inline">\((m,\pi)\)</span>. On considère la petite base de données fictive suivante :</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;"><code>x</code></th>
<th style="text-align: center;">Nombre d’essais</th>
<th style="text-align: center;">Nombre de réussites</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a)</strong> Ajuster les modèles <span class="math display">\[M_0:\mathrm{logit}(\pi)=\beta_0\]</span> et <span class="math display">\[M_1:\mathrm{logit}(\pi)=\beta_0+\beta_1 x\]</span> en utilisant les données sous forme groupée (Binomiale).</p>
<p><strong>b)</strong> Ajuster les modèles <span class="math display">\[M_0:\mathrm{logit}(\pi)=\beta_0\]</span> et <span class="math display">\[M_1:\mathrm{logit}(\pi)=\beta_0+\beta_1 x\]</span> en utilisant les données sous forme individuelles (Bernoulli).</p>
<p><strong>c)</strong> Comparer les estimations et les écart-types des coefficients, ainsi que les déviances pour les modèles ajustés en a) avec ceux ajustés en b). Commenter.</p>
<p><strong>d)</strong> Comparer les log-vraisemblances pour les modèles en a) avec ceux en b). Expliquer pourquoi les estimations des paramètres sont équivalentes.</p>
<p><strong>e)</strong> Faire une analyse de déviance pour déterminer si le modèle <span class="math inline">\(M_0\)</span> est une simplification adéquate du modèle <span class="math inline">\(M_1\)</span>. Obtient-on les mêmes résultats avec les modèles en a) et en b)? Pourquoi?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Les données sous forme groupées sont codées comme suit en R :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Success <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">4</span>,<span class="dv">3</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>alors que les données individuelles sont programmées de la façon suivante :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>xv2 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>,<span class="at">each=</span><span class="dv">4</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Successv2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>a)</strong> On trouve les résultats suivants :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>M0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Success,Trials<span class="sc">-</span>Success) <span class="sc">~</span> <span class="dv">1</span>,binomial) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Success,Trials<span class="sc">-</span>Success) <span class="sc">~</span> x,binomial) </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M0) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Success, Trials - Success) ~ 1, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)   0.3365     0.5855   0.575    0.566

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6.2568  on 2  degrees of freedom
Residual deviance: 6.2568  on 2  degrees of freedom
AIC: 11.945

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Success, Trials - Success) ~ x, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)   -1.503      1.181  -1.272   0.2034  
x              2.060      1.130   1.823   0.0683 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6.2568  on 2  degrees of freedom
Residual deviance: 0.9844  on 1  degrees of freedom
AIC: 8.6722

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>b)</strong> On trouve les résultats suivants :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>M0v2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Successv2 <span class="sc">~</span> <span class="dv">1</span>,binomial) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>M1v2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Successv2 <span class="sc">~</span> xv2,binomial) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M0v2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Successv2 ~ 1, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)   0.3365     0.5855   0.575    0.566

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 16.301  on 11  degrees of freedom
Residual deviance: 16.301  on 11  degrees of freedom
AIC: 18.301

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1v2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Successv2 ~ xv2, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)   -1.503      1.181  -1.272   0.2033  
xv2            2.060      1.130   1.823   0.0682 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 16.301  on 11  degrees of freedom
Residual deviance: 11.028  on 10  degrees of freedom
AIC: 15.028

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>c)</strong> Les estimations des coefficients sont exactement les mêmes pour les deux façons de programmer les données. Cela est attendu. Les écart-types sont également équivalents peu importe si on utilise les données groupées ou non. Par contre, les déviances sont beaucoup plus élevées dans le modèle avec les données individuelles. Cela pourrait être relié au nombre de degrés de liberté, qui est aussi supérieur dans le cas des données individuelles puisqu’on a 12 observations au lieu de 3.</p>
<p><strong>d)</strong> L’expression de la log vraisemblance pour un modèle binomial est <span class="math display">\[
\begin{aligned} l&amp;=\sum_{i=1}^n y_i \eta_i - m_i \log(1+e^{\eta_i})+\log\begin{pmatrix} m_i\\ y_i\end{pmatrix}. \end{aligned}
\]</span></p>
<p>On voit donc facilement que la différence entre la log-vraisemblance dans le modèle avec données groupées est le terme constant <span class="math inline">\(\log\begin{pmatrix} m_i\\ y_i\end{pmatrix}\)</span>, qui n’est pas présent avec les données Bernoulli. Par conséquent, l’estimation des paramètres est la même dans les deux modèles, puisque lorsque l’on dérive la log-vraisemblance, ce terme constant ne joue aucun rôle.</p>
<p><strong>e)</strong> L’analyse de déviance donne exactement le même résultat dans les deux cas. Pour les données Binomiales, on a que <span class="math display">\[ \Delta Deviance = 6.2568 - 6.2568 =5.2724 &gt; \chi^2_{95\%}(1),\]</span> alors on rejette l’hypothèse nulle que le modèle nul est une simplification adéquate du modèle incluant la variable exogène <span class="math inline">\(x\)</span>. Pour les données Bernoulli, on a aussi que <span class="math display">\[ \Delta Deviance = 16.301 - 11.028 =5.2724 &gt; \chi^2_{95\%}(1).\]</span> Cela montre que la façon d’entrer les données a un impact seulement sur les tests d’adéquation du modèle, pour vérifier la qualité de l’ajustement. En fait, la déviance n’est pas une statistique appropriée pour évaluer la qualité de l’ajustement pour des données Bernoulli.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M0,M1)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: cbind(Success, Trials - Success) ~ 1
Model 2: cbind(Success, Trials - Success) ~ x
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
1         2     6.2568                       
2         1     0.9844  1   5.2724  0.02167 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M0v2,M1v2)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Successv2 ~ 1
Model 2: Successv2 ~ xv2
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
1        11     16.301                       
2        10     11.028  1   5.2724  0.02167 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.841459</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-binom-age_kyphosis" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-binom-age_kyphosis"><span class="header-section-number">7.3</span> Effet de l’âge sur la kyphosis</h2>
<p>Une étude sur une condition de la colonne vertébrale (kyphosis) survenant après une opération a été réalisée par Hastie et Tibshirani (1990). On s’intéresse à l’effet de la variable explicative <code>age</code> (en mois) au moment de l’opération, sur la probabilité d’avoir cette mauvaise condition. Les données peuvent être programmées en R avec les deux commandes suivantes :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">15</span>,<span class="dv">42</span>,<span class="dv">52</span>,<span class="dv">59</span>,<span class="dv">73</span>,<span class="dv">82</span>,<span class="dv">91</span>,<span class="dv">96</span>,<span class="dv">105</span>,<span class="dv">114</span>,<span class="dv">120</span>,<span class="dv">121</span>,<span class="dv">128</span>,<span class="dv">130</span>,<span class="dv">139</span>,<span class="dv">139</span>,<span class="dv">157</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">11</span>,<span class="dv">18</span>,<span class="dv">22</span>,<span class="dv">31</span>,<span class="dv">37</span>,<span class="dv">61</span>,<span class="dv">72</span>,<span class="dv">81</span>,<span class="dv">97</span>,<span class="dv">112</span>,<span class="dv">118</span>,<span class="dv">127</span>,<span class="dv">131</span>,<span class="dv">140</span>,<span class="dv">151</span>,<span class="dv">159</span>,<span class="dv">177</span>,<span class="dv">206</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>kyp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">18</span>),<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">22</span>))</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>a)</strong> Ajuster un modèle de régression logistique sur ces données Bernoulli. Effectuer un test de Wald sur l’effet de l’âge et interpréter.</p>
<p><strong>b)</strong> Tracer le graphique des données. Que remarquez-vous?</p>
<p><strong>c)</strong> Ajouter le carré de l’âge comme variable explicative dans le modèle. Est-ce que l’âge a un impact significatif sur la probabilité d’avoir le “kyphosis” après l’opération?</p>
<p><strong>d)</strong> Tracer les courbes des modèles ajustés. Interpréter.</p>
<p><strong>e)</strong> Utiliser le critère AIC pour comparer les deux modèles.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Le modèle de régression logistique est <span class="math inline">\(\log\left(\frac{\pi_i}{1-\pi_i}\right)=\eta_i=\beta_0+\beta_1 \times {\mathrm age}\)</span>. On trouve les estimations des paramètres en R. Les hypothèses du test de Wald sont</p>
<p><span class="math display">\[
H_0~: \beta_1=0 \text{ versus } H_1~: \beta_1\ne0.
\]</span></p>
<p>La statistique est 0.734 et le seuil observé du test est 46.3 %, ce qui n’est pas significatif. On ne peut donc pas rejeter l’hypothèse nulle que <span class="math inline">\(\beta_1=0\)</span>. Cela signifie qu’il n’y a pas de preuves dans ces données que l’âge a un impact significatif sur la probabilité d’être atteint de kyphosis après une opération.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="fu">glm</span>(kyp <span class="sc">~</span> age,<span class="at">family=</span>binomial)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(moda)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = kyp ~ age, family = binomial)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)
(Intercept) -0.572693   0.602395  -0.951    0.342
age          0.004296   0.005849   0.734    0.463

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 55.051  on 39  degrees of freedom
Residual deviance: 54.504  on 38  degrees of freedom
AIC: 58.504

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>b)</strong> On trace le graphique des données : <code>plot(age,kyp,pch=16)</code>.</p>
<p>Le résultat est montré dans la figure <a href="#fig-binom-kyp" class="quarto-xref"><span>7.1</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-binom-kyp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-kyp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="binom_files/figure-html/fig-binom-kyp-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binom-kyp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Graphique des données
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>c)</strong> Le modèle est maintenant <span class="math inline">\(\log\left(\frac{\pi_i}{1-\pi_i}\right)=\eta_i=\beta_0+\beta_1 age+\beta_2 age^2\)</span>. On trouve les estimations des paramètres en R. Les tests de Wald pour <span class="math inline">\(\beta_1\)</span> et <span class="math inline">\(\beta_2\)</span> sont tous deux significatifs à 5 %. On trouve donc que l’âge a un effet significatif sur la probabilité d’être atteint de kyphosis après l’opération.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>modb <span class="ot">&lt;-</span> <span class="fu">glm</span>(kyp<span class="sc">~</span>age<span class="sc">+</span><span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>),<span class="at">family=</span>binomial)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modb)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = kyp ~ age + I(age^2), family = binomial)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -2.0462547  0.9943478  -2.058   0.0396 *
age          0.0600398  0.0267808   2.242   0.0250 *
I(age^2)    -0.0003279  0.0001564  -2.097   0.0360 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 55.051  on 39  degrees of freedom
Residual deviance: 48.228  on 37  degrees of freedom
AIC: 54.228

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>d)</strong> On trace le graphique des données et on ajoute les courbes de probabilités ajustées. Le résultat est montré dans la figure <a href="#fig-binom-kyp2" class="quarto-xref"><span>7.2</span></a>. On ne voit pas grand chose d’intéressant, sauf que le modèle en a) semble parfaitement inutile. On peut grouper les données par catégorie d’âge plutôt que de laisser les données individuelles pour mieux voir l’ajustement. Le graphique des données groupées est montré dans la figure <a href="#fig-binom-kyp3" class="quarto-xref"><span>7.3</span></a>. On observe que le modèle quadratique s’ajuste beaucoup mieux aux données.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-binom-kyp2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-kyp2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="binom_files/figure-html/fig-binom-kyp2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binom-kyp2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Graphique des données et probabilités ajustées. En noir: modèle a), en rouge pointillé: modèle c).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-binom-kyp3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-kyp3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="binom_files/figure-html/fig-binom-kyp3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binom-kyp3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Graphique des données groupées et probabilités ajustées. En noir: modèle a), en rouge pointillé: modèle c).
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>e)</strong> Le critère AIC est donné dans la sortie R. Le critère AIC pour le modèle c) est 54.228 et est inférieur à celui pour le modèle a), ce qui soutient encore une fois que le modèle avec le terme <span class="math inline">\(age^2\)</span> est préférable.</p>
</div>
</div>
</div>
</section>
<section id="sec-binom-cancer_peau_st_paul" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-binom-cancer_peau_st_paul"><span class="header-section-number">7.4</span> Cas de cancer de la peau parmi des femmes à St-Paul</h2>
<p>Les données contenues dans le fichier <code>skin.txt</code> montrent le nombre de cas de cancer de la peau parmi des femmes à St-Paul, Minnesota et à Forth Worth, Texas. On s’attend normalement à ce que l’exposition au soleil soit plus forte au Texas qu’au Minnesota. Dans les données, la variable <code>town</code> vaut 0 pour St-Paul et 1 pour Forth Worth. On a également la population et le groupe d’âge.</p>
<p><strong>a)</strong> Ajuster un modèle de régression logistique <code>town+age</code> pour ces données. Est-ce que les variables sont significatives?</p>
<p><strong>b)</strong> A-t-on une indication dans ces données que l’exposition au soleil augmente la probabilité d’être atteinte du cancer de la peau?</p>
<p><strong>c)</strong> Comparer les probabilités ajustées (et écarts-types) pour des femmes de 45 ans vivant à St-Paul versus vivant à Fort Worth.</p>
<p><strong>d)</strong> Utiliser un modèle de Poisson avec lien canonique, de façon appropriée, pour modéliser ces données. Arrive-t-on aux mêmes conclusions?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Le modèle de régression logistique est <span class="math inline">\(\log\left(\frac{\pi_i}{1-\pi_i}\right)=\eta_i=\beta_0+\beta^{town}+\beta^{age}\)</span>. On y va :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>skin <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/Skin.txt"</span>,<span class="at">header=</span><span class="cn">TRUE</span>) </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Cases,Population<span class="sc">-</span>Cases) <span class="sc">~</span> Town<span class="sc">+</span>Age,<span class="at">family=</span>binomial,<span class="at">data=</span>skin)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Cases, Population - Cases) ~ Town + Age, 
    family = binomial, data = skin)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -11.69364    0.44923 -26.030  &lt; 2e-16 ***
Town          0.85492    0.05969  14.322  &lt; 2e-16 ***
Age25-34      2.62915    0.46747   5.624 1.86e-08 ***
Age35-44      3.84627    0.45467   8.459  &lt; 2e-16 ***
Age45-54      4.59538    0.45104  10.188  &lt; 2e-16 ***
Age55-64      5.08901    0.45031  11.301  &lt; 2e-16 ***
Age65-74      5.65031    0.44976  12.563  &lt; 2e-16 ***
Age75-84      6.20887    0.45756  13.570  &lt; 2e-16 ***
Age85+        6.18346    0.45783  13.506  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2330.4637  on 14  degrees of freedom
Residual deviance:    5.1509  on  6  degrees of freedom
AIC: 110.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Selon les tests de Wald, tous les paramètres sont hautement significatifs.</p>
<p><strong>b)</strong> Oui, le coefficient lié à la variable <code>Town</code> est positif. Cela signifie que d’être à Fort Worth augmente <span class="math inline">\(\eta_i\)</span>, et puisque <span class="math inline">\(\pi_i=\frac{e^{\eta_i}}{1+e^{\eta_i}}\)</span>, cela augmente aussi la probabilité d’avoir le cancer de la peau.</p>
<p><strong>c)</strong> Pour la femme vivant à St-Paul, on a <span class="math display">\[
\hat{\pi}=\frac{\exp(-11.69364+4.595    38)}{1+\exp(-11.69364+4.59538)}=0.00082586.
\]</span></p>
<p>Pour la femme vivant à Fort Worth, on a <span class="math display">\[
\hat{\pi}=\frac{\exp(-11.69364+0.85492+4.59538)}{1+\exp(-11.69364+0.85492+4.59538)}=0.0019396.
\]</span></p>
<p>On trouve donc que la deuxième probabilité est plus élevée que la première. En R, on peut utiliser la fonction <code>predict</code> :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod1,<span class="fu">data.frame</span>(<span class="at">Town=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">Age=</span><span class="fu">rep</span>(<span class="st">"45-54"</span>,<span class="dv">2</span>)),<span class="at">type=</span><span class="st">"response"</span>,<span class="at">se.fit=</span><span class="cn">TRUE</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$fit
           1            2 
0.0008258624 0.0019395844 

$se.fit
           1            2 
6.051739e-05 1.173087e-04 

$residual.scale
[1] 1</code></pre>
</div>
</div>
<p><strong>d)</strong> On peut utiliser un modèle de Poisson avec un terme offset égal au logarithme de la population. On obtient les mêmes conclusions quant à l’effet de la ville sur la probabilité d’être atteinte du cancer de la peau. Le modèle de Poisson semble adéquat si on se base sur la déviance. Dans ce cas, les populations sont très élevées, alors le modèle de Poisson est une excellente approximation pour le modèle Binomial.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Cases <span class="sc">~</span> Town<span class="sc">+</span>Age<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Population)),<span class="at">family=</span>poisson,<span class="at">data=</span>skin) </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Cases ~ Town + Age + offset(log(Population)), family = poisson, 
    data = skin)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -11.69207    0.44922 -26.028  &lt; 2e-16 ***
Town          0.85269    0.05962  14.302  &lt; 2e-16 ***
Age25-34      2.62899    0.46746   5.624 1.87e-08 ***
Age35-44      3.84558    0.45466   8.458  &lt; 2e-16 ***
Age45-54      4.59381    0.45103  10.185  &lt; 2e-16 ***
Age55-64      5.08638    0.45030  11.296  &lt; 2e-16 ***
Age65-74      5.64569    0.44975  12.553  &lt; 2e-16 ***
Age75-84      6.20317    0.45751  13.558  &lt; 2e-16 ***
Age85+        6.17568    0.45774  13.492  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2327.2912  on 14  degrees of freedom
Residual deviance:    5.2089  on  6  degrees of freedom
AIC: 110.19

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod2,<span class="fu">data.frame</span>(<span class="at">Town=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">Age=</span><span class="fu">rep</span>(<span class="st">"45-54"</span>,<span class="dv">2</span>),<span class="at">Population=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">2</span>)),<span class="at">type=</span><span class="st">"response"</span>,<span class="at">se.fit=</span><span class="cn">TRUE</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$fit
           1            2 
0.0008265387 0.0019390253 

$se.fit
           1            2 
6.055942e-05 1.174031e-04 

$residual.scale
[1] 1</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-binom-pearson_statistique" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sec-binom-pearson_statistique"><span class="header-section-number">7.5</span> Statistique de Pearson pour le modèle binomial</h2>
<p>Soient <span class="math inline">\(Y_i\sim Bin(m_i,\pi_i),\)</span> pour <span class="math inline">\(i=1,\ldots,n\)</span> et <span class="math inline">\(Y_i\bot Y_j\)</span> pour <span class="math inline">\(i \ne j\)</span>. On considère le modèle où <span class="math inline">\(\pi_1=\cdots=\pi_n=\pi\)</span>. On a un échantillon d’observations <span class="math inline">\(y_1,\ldots,y_n\)</span>.</p>
<p><strong>a)</strong> Montrer que l’estimateur du maximum de vraisemblance de <span class="math inline">\(\pi\)</span> est <span class="math display">\[\hat{\pi}=\frac{\sum_{i=1}^n y_i}{\sum_{i=1}^n m_i}.\]</span></p>
<p><strong>b)</strong> Si <span class="math inline">\(m_i=1\)</span> pour <span class="math inline">\(i=1,\ldots,n\)</span>, alors montrer que la statistique de Pearson est égale à <span class="math inline">\(X^2=n\)</span>. Cela signifie que la statistique de Pearson n’est pas utile pour tester l’adéquation du modèle lorsque les données ne sont pas groupées.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> On a que la vraisemblance est</p>
<p><span class="math display">\[
\mathcal{L}=\prod_{i=1}^n \begin{pmatrix} m_i \\ y_i \end{pmatrix} \pi^{y_i}(1-\pi)^{m_i-y_i}.
\]</span></p>
<p>La log-vraisemblance est</p>
<p><span class="math display">\[
\begin{aligned} l&amp;=\sum_{i=1}^n \log\begin{pmatrix} m_i \\ y_i \end{pmatrix}+ y_i\log(\pi)+(m_i-y_i)\log(1-\pi)\\ &amp;=\sum_{i=1}^n \log\begin{pmatrix} m_i \\ y_i \end{pmatrix}+ y_i\log\left(\frac{\pi}{1-\pi}\right)+m_i\log(1-\pi). \end{aligned}
\]</span></p>
<p>On dérive par rapport à <span class="math inline">\(\pi\)</span> pour maximiser :</p>
<p><span class="math display">\[
\begin{aligned} \frac{\partial l}{\partial \pi}&amp;=\sum_{i=1}^n y_i \frac{1-\pi}{\pi}\frac{1}{(1-\pi)^2}-\sum_{i=1}^n \frac{m_i}{1-\pi}.\\ &amp;=\sum_{i=1}^n y_i \frac{1}{\pi(1-\pi)}-\sum_{i=1}^n \frac{m_i}{1-\pi}. \end{aligned}
\]</span></p>
<p>Alors,</p>
<p><span class="math display">\[
\begin{aligned} 0&amp;=\sum_{i=1}^n y_i \frac{1}{\hat{\pi}(1-\hat{\pi})}-\sum_{i=1}^n \frac{m_i}{1-\hat{\pi}}\\ 0&amp;=\sum_{i=1}^n y_i \frac{1}{\hat{\pi}}-\sum_{i=1}^n m_i\\ \hat{\pi}&amp;=\frac{\sum_{i=1}^n y_i}{\sum_{i=1}^n m_i}. \end{aligned}
\]</span></p>
<p><strong>b)</strong> Si <span class="math inline">\(m_i=1\forall i\)</span> et <span class="math inline">\(\hat{\pi}_i=\hat{\pi}\forall i\)</span>, alors la statistique de Pearson est</p>
<p><span class="math display">\[
X^2=\sum_{i=1}^n \frac{(y_i-\hat{\pi})^2}{\hat{\pi}(1-\hat{\pi})}.
\]</span></p>
<p>Or, on a que <span class="math inline">\(\sum_{i=1}^n m_i=n\)</span> et</p>
<p><span class="math display">\[
\begin{aligned} \hat{\pi}(1-\hat{\pi}) &amp;=\frac{\sum_{i=1}^n y_i}{n} \frac{\left(n-\sum_{i=1}^n y_i\right)}{n}\\ &amp;=\frac{\sum_{i=1}^n y_i\left(n-\sum_{i=1}^n y_i\right)}{n^2}. \end{aligned}
\]</span></p>
<p>Donc, <span class="math display">\[
\begin{aligned} X^2&amp;=n^2  \frac{\sum_{i=1}^n(y_i-\hat{\pi})^2}{\sum_{i=1}^n y_i\left(n-\sum_{i=1}^n y_i\right)}\\ &amp;=n^2  \frac{\sum_{i=1}^n y_i-2\hat{\pi}\sum_{i=1}^n y_i+n\hat{\pi}^2}{\sum_{i=1}^n y_i\left(n-\sum_{i=1}^n y_i\right)}\\ &amp;=n^2  \frac{\sum_{i=1}^n y_i-\frac{2}{n}\left(\sum_{i=1}^n y_i\right)^2+\frac{n}{n^2}\left(\sum_{i=1}^n y_i\right)^2}{\sum_{i=1}^n y_i\left(n-\sum_{i=1}^n y_i\right)}\\ &amp;=  n\frac{n \sum_{i=1}^n y_i-\left(\sum_{i=1}^n y_i\right)^2}{\sum_{i=1}^n y_i\left(n-\sum_{i=1}^n y_i\right)}\\ &amp;=n. \end{aligned}
\]</span></p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapitres/comptage.html" class="pagination-link" aria-label="Modélisation de données de comptage">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>