<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Modélisation de données de comptage – ACT2003 — Recueil d'exercices</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapitres/binom.html" rel="next">
<link href="../chapitres/glm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a522afb83bf8ae494942cf1b0ac9d4c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<script>
window.MathJax = {
  tex: {
    macros: {
      esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      ex:     "\\mathbb{E}",
      var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      vr:     "\\mathrm{Var}",
      prob:   "\\Pr",
      Prob:   "\\Pr",
      cov:    ["\\mathrm{Cov}\\!\\left(#1\\right)",1],
      Cov:    "\\mathrm{Cov}",
      SST:    "\\mathrm{SST}",
      SSR:    "\\mathrm{SSR}",
      SSE:    "\\mathrm{SSE}",
      MSE:    "\\mathrm{MSE}",
      MSR:    "\\mathrm{MSR}",
      d:      "\\mathrm{d}",
      bm:     ["\\boldsymbol{#1}", 1],
      yvec:   "\\mathbf{Y}",
      xvec:   "\\mathbf{x}",
      Xmat:   "\\mathbf{X}",
      betavec: "\\boldsymbol{\\beta}",
      epsvec: "\\boldsymbol{\\varepsilon}",
      mat:    ["\\mathbf{#1}", 1],
      varmat:    ["\\mathbf{V} ( #1 )", 1],
      hatbetavec: "\\boldsymbol{\\hat{\\beta}}",
      hatepsvec: "\\boldsymbol{\\hat{\\varepsilon}}",
      Norm: "\\mathcal{N}",
      diag: "\\mathrm{diag}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/comptage.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACT2003 — Recueil d’exercices</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Régression linéaire simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Régression linéaire multiple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sélection de modèle et régression régularisée</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/comptage.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sec-comptage-glm_poisson_r" id="toc-sec-comptage-glm_poisson_r" class="nav-link active" data-scroll-target="#sec-comptage-glm_poisson_r"><span class="header-section-number">6.1</span> Ajustement d’un GLM Poisson en R</a></li>
  <li><a href="#sec-comptage-demo_nb" id="toc-sec-comptage-demo_nb" class="nav-link" data-scroll-target="#sec-comptage-demo_nb"><span class="header-section-number">6.2</span> Mélange Poisson gamma</a></li>
  <li><a href="#sec-comptage-glm_poisson_groupes" id="toc-sec-comptage-glm_poisson_groupes" class="nav-link" data-scroll-target="#sec-comptage-glm_poisson_groupes"><span class="header-section-number">6.3</span> GLM Poisson avec deux groupes</a></li>
  <li><a href="#sec-comptage-taux_imperfection" id="toc-sec-comptage-taux_imperfection" class="nav-link" data-scroll-target="#sec-comptage-taux_imperfection"><span class="header-section-number">6.4</span> Taux d’imperfection</a></li>
  <li><a href="#sec-comptage-berkeley_admission" id="toc-sec-comptage-berkeley_admission" class="nav-link" data-scroll-target="#sec-comptage-berkeley_admission"><span class="header-section-number">6.5</span> Admission à l’Université Berkeley</a></li>
  <li><a href="#sec-comptage-deces_cancer_poumon" id="toc-sec-comptage-deces_cancer_poumon" class="nav-link" data-scroll-target="#sec-comptage-deces_cancer_poumon"><span class="header-section-number">6.6</span> Décès dus au cancer du poumon</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/comptage.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-comptage-glm_poisson_r" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-comptage-glm_poisson_r"><span class="header-section-number">6.1</span> Ajustement d’un GLM Poisson en R</h2>
<p>Ajuster un modèle de Poisson avec lien logarithmique au données <code>esoph</code> du paquetage <code>datasets</code> en R. À partir du modèle avec effets principaux et les interactions de second ordre</p>
<p><code>agegp+alcgp+tobgp+agegp:alcgp+agegp:tobgp+alcgp:tobg</code>, faire une analyse de déviance pour trouver le modèle le plus approprié.</p>
<p>Y a-t-il une interaction qui est significative dans le modèle? Expliquer.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On ajuste d’abord le modèle avec les effets principaux et les interactions.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ncases <span class="sc">~</span> <span class="fu">factor</span>(agegp)<span class="sc">*</span>(<span class="fu">factor</span>(alcgp)<span class="sc">+</span><span class="fu">factor</span>(tobgp))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>           <span class="sc">+</span><span class="fu">factor</span>(alcgp)<span class="sc">:</span><span class="fu">factor</span>(tobgp), <span class="at">family=</span>poisson, <span class="at">data=</span>esoph)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted rates numerically 0 occurred</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit1)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted rates numerically 0 occurred</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: poisson, link: log

Response: ncases

Terms added sequentially (first to last)

                            Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                                           87    262.926              
factor(agegp)                5  138.256        82    124.670 &lt; 2.2e-16 ***
factor(alcgp)                3   24.106        79    100.564 2.374e-05 ***
factor(tobgp)                3   22.169        76     78.395 6.016e-05 ***
factor(agegp):factor(alcgp) 15   32.417        61     45.979  0.005648 ** 
factor(agegp):factor(tobgp) 15   18.109        46     27.870  0.256987    
factor(alcgp):factor(tobgp)  9    7.658        37     20.212  0.568932    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">9</span>) <span class="do">## rejette alcgp:tobgp</span></span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.91898</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">15</span>) <span class="do">## rejette agegp:tobgp mais conserve agegp:alcgp</span></span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.99579</code></pre>
</div>
</div>
<p>On trouve donc que l’interaction entre la consommation d’alcool et de tabac n’est pas significative parce que <span class="math display">\[
\begin{aligned}
\Delta Deviance = 7.658 &lt; \chi^{2}_{(9;0.95)}=16.92.
\end{aligned}
\]</span> Cela signifie que le modèle <code>agegp*(alcgp+tobgp)</code> est une simplification adéquate du modèle <code>agegp+alcgp+tobgp+agegp.alcgp+agegp.tobgp+alcgp.tobgp</code>. De plus, on peut enlever l’interaction entre l’âge et la consommation de tabac : <span class="math display">\[
\begin{aligned}
\Delta Deviance = 18.109 &lt; \chi^{2}_{(15;0.95)}=25.
\end{aligned}
\]</span> Cela signifie que le modèle <code>agegp*alcgp+tobgp</code> est une simplification adéquate du modèle <code>agegp*(alcgp+tobgp)</code>. Toutefois, on ne peut pas enlever l’autre terme d’interaction, car <span class="math display">\[
\begin{aligned}
\Delta Deviance = 32.417 &gt; \chi^{2}_{(15;0.95)}=25.
\end{aligned}
\]</span> Si on tente de remettre l’interaction entre la consommation d’alcool et de tabac dans le modèle, on trouve qu’elle n’est toujours pas significative :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ncases <span class="sc">~</span> agegp <span class="sc">*</span> alcgp <span class="sc">+</span> tobgp,<span class="at">family=</span>poisson,<span class="at">data=</span>esoph)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">update</span>(fit1, <span class="sc">~</span>.<span class="sc">-</span><span class="fu">factor</span>(agegp)<span class="sc">:</span><span class="fu">factor</span>(tobgp))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit2,fit3)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: ncases ~ agegp * alcgp + tobgp
Model 2: ncases ~ factor(agegp) + factor(alcgp) + factor(tobgp) + factor(agegp):factor(alcgp) + 
    factor(alcgp):factor(tobgp)
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1        61     45.979                     
2        52     38.973  9    7.006   0.6365</code></pre>
</div>
</div>
<p>Par conséquent, le modèle final est <code>agegp*alcgp+tobgp</code>. Cela signifie que l’effet de consommer de l’alcool sur l’occurence du cancer de l’oesophage est différent pour chaque groupe d’âge.</p>
</div>
</div>
</div>
</section>
<section id="sec-comptage-demo_nb" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-comptage-demo_nb"><span class="header-section-number">6.2</span> Mélange Poisson gamma</h2>
<p>Montrer que si <span class="math inline">\(Y|Z=z\sim Poisson(\mu z)\)</span>, et <span class="math inline">\(Z\sim Gamma(\theta_z,\theta_z)\)</span>, alors <span class="math inline">\(Y\sim BinNeg(\mu,\theta_z)\)</span>, soit <span class="math display">\[
f(y)=\frac{\Gamma(\theta_z+y)}{\Gamma(\theta_z)y!}\left(\frac{\mu}{\mu+\theta_z}\right)^y\left(\frac{\theta_z}{\mu+\theta_z}\right)^{\theta_z}, y=0,1,\ldots
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On doit intégrer la densité conditionnelle Poisson sur <span class="math inline">\(z\)</span>.</p>
<p>On veut prouver que <span class="math inline">\(Y \sim \text{BinNeg}(\mu, \theta_{z})\)</span> avec la fonction de densité suivante : <span class="math display">\[
\begin{aligned}
    f_{Y}(y)
    &amp;=  \int_{0}^{\infty} f_{Y|Z = z}(y | z) \cdot g_{Z}(z) dz  \\
    &amp;=  \int_{0}^{\infty} \frac{(\mu z)^{y} e^{-\mu z}}{y!} \cdot \frac{z^{\theta_{z} - 1} \theta_{z}^{\theta_{z}} e^{-\theta_{z} z}}{\Gamma(\theta_{z})} dz    \\
    &amp;=  \frac{(\theta_{z} + y - 1)!}{(\theta_{z} + y - 1 - y)! y!} \cdot \frac{\theta_{z}^{\theta_{z}} \mu^{y}}{(\mu + \theta_{z})^{\theta_{z} + y}}
            \underset{1}{\underbrace{\int_{0}^{\infty} \frac{z^{\theta_{z} + y - 1} \textrm{e}^{-(\mu + \theta_{z})z}}{\Gamma(\theta_{z} + y)} (\mu + \theta_{z})^{\theta_{z} + y} dz}}
\end{aligned}
\]</span></p>
<p>On trouve donc que <span class="math display">\[
\begin{aligned}
f_{Y}(y)
    &amp;=  \binom{\theta_{z} + y - 1}{y} \left(\frac{\mu}{\mu + \theta_{z}}\right)^y \left(\frac{\theta_{z}}{\mu + \theta_{z}}\right)^{\theta_{z}} \\
    &amp;=  \frac{\Gamma(\theta_{z} + y)}{\Gamma(\theta_z) y!} \left(\frac{\mu}{\mu + \theta_{z}}\right)^y \left(\frac{\theta_{z}}{\mu + \theta_{z}}\right)^{\theta_{z}}.
\end{aligned}
\]</span></p>
<p>Et donc, <span class="math inline">\(Y \sim \text{BinNeg}(\mu, \theta_{z})\)</span> où <span class="math inline">\(y \in \{0,1,\ldots\}\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-comptage-glm_poisson_groupes" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-comptage-glm_poisson_groupes"><span class="header-section-number">6.3</span> GLM Poisson avec deux groupes</h2>
<p>On suppose que <span class="math inline">\(Y_i\)</span> suit une Poisson avec <span class="math inline">\(g(\mu_i)=\beta_0+\beta_1x_i,\)</span> où <span class="math inline">\(x_i=1,\)</span> pour <span class="math inline">\(i=1,\ldots,n_A\)</span> (groupe A) et <span class="math inline">\(x_i=0,\)</span> pour <span class="math inline">\(i=n_A+1,\ldots,n_A+n_B\)</span> (groupe B). Montrer que, pour toute fonction de lien <span class="math inline">\(g\)</span> continue, l’estimation du GLM par maximum de vraisemblance implique que les moyennes ajustées <span class="math inline">\(\hat{\mu}_A\)</span> et <span class="math inline">\(\hat{\mu}_B\)</span> sont égales aux moyennes empiriques dans l’échantillon.</p>
<p><em>Indice:</em> La dérivée de la réciproque d’une fonction continue <span class="math inline">\(g\)</span> est <span class="math inline">\(\frac{1}{g'\circ g^{-1}}\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On note <span class="math inline">\(n=n_A+n_B\)</span>. La vraisemblance pour ce GLM est <span class="math display">\[
\begin{aligned}
\mathcal{L}(\beta_0,\beta_1)&amp;=\prod_{i=1}^n \exp(y_i\log(\mu_i)-\mu_i+\text{cte})\\
&amp;=\prod_{i=1}^n \exp(y_i\log(g^{-1}(\eta_i))-g^{-1}(\eta_i)+\text{cte}).
\end{aligned}
\]</span> La log-vraisemblance est donc : <span class="math display">\[
\begin{aligned}
\ell(\beta_0,\beta_1)&amp;=\sum_{i=1}^n (y_i\log(g^{-1}(\eta_i))-g^{-1}(\eta_i)+\text{cte}).
\end{aligned}
\]</span> On dérive par rapport à <span class="math inline">\(\beta_0\)</span> et <span class="math inline">\(\beta_1\)</span> : <span class="math display">\[
\begin{aligned}
\frac{\partial \ell(\beta_0,\beta_1)}{\partial\beta_0}&amp;=\sum_{i=1}^n (y_i\frac{1}{g^{-1}(\eta_i)g'(g^{-1}(\eta_i))}-\frac{1}{g'(g^{-1}(\eta_i))})\\
&amp;=\sum_{i=1}^n \frac{(y_i-g^{-1}(\eta_i))}{g^{-1}(\eta_i)g'(g^{-1}(\eta_i))}\\
\frac{\partial \ell(\beta_0,\beta_1)}{\partial\beta_1}&amp;=\sum_{i=1}^n (y_i\frac{x_i}{g^{-1}(\eta_i)g'(g^{-1}(\eta_i))}-\frac{x_i}{g'(g^{-1}(\eta_i))})\\
&amp;=\sum_{i=1}^n \frac{ x_i(y_i-g^{-1}(\eta_i))}{g^{-1}(\eta_i)g'(g^{-1}(\eta_i))}.
\end{aligned}
\]</span> On égalise à 0 pour obtenir le système d’équations à résoudre. <span class="math display">\[
\begin{aligned}
0&amp;=\sum_{i=1}^n \frac{(y_i-g^{-1}(\hat{\eta}_i))}{g^{-1}(\hat{\eta}_i)g'(g^{-1}(\hat{\eta}_i))}\\
0&amp;=\sum_{i=1}^n \frac{ x_i(y_i-g^{-1}(\hat{\eta}_i))}{g^{-1}(\hat{\eta}_i)g'(g^{-1}(\hat{\eta}_i))}
\end{aligned}
\]</span> On utilise que <span class="math inline">\(x_i=0 \forall i \in (n_A+1,...,n_A+n_B)\)</span> : <span class="math display">\[
\begin{aligned}
0&amp;=\sum_{i=1}^{n_A+n_B} \frac{(y_i-g^{-1}(\hat{\eta}_i))}{g^{-1}(\hat{\eta}_i)g'(g^{-1}(\hat{\eta}_i))}\\
0&amp;=\sum_{i=1}^{n_A} \frac{ (y_i-g^{-1}(\hat{\eta}_i))}{g^{-1}(\hat{\eta}_i)g'(g^{-1}(\hat{\eta}_i))}\\
\Rightarrow 0&amp;= \sum_{i=n_A+1}^{n_A+n_B} \frac{ (y_i-g^{-1}(\hat{\eta}_i))}{g^{-1}(\hat{\eta}_i)g'(g^{-1}(\hat{\eta}_i))}.
\end{aligned}
\]</span> Aussi, <span class="math inline">\(\forall i \in (1,...,n_A), \hat{\eta}_i=\hat{\beta}_0+\hat{\beta}_1\)</span>, ce qui ne dépend pas de <span class="math inline">\(i\)</span>. Le dénominateur ne dépend pas de <span class="math inline">\(i\)</span> et peut sortir de la somme et s’annuler. De même, <span class="math inline">\(\forall i \in (n_A+1,...,n_A+n_B), \hat{\eta}_i=\hat{\beta}_0\)</span>, ce qui ne dépend pas de <span class="math inline">\(i\)</span>. Le dénominateur ne dépend pas de <span class="math inline">\(i\)</span> et peut sortir de la somme et s’annuler. On obtient donc les équations : <span class="math display">\[
\begin{aligned}
0&amp;=\sum_{i=1}^{n_A} (y_i-g^{-1}(\hat{\eta}_i))\\
0&amp;= \sum_{i=n_A+1}^{n_A+n_B}  (y_i-g^{-1}(\hat{\eta}_i)).
\end{aligned}
\]</span> Finalement, <span class="math inline">\(g^{-1}(\hat{\eta}_i)=\hat{\mu}_i\)</span> par définition. Alors, <span class="math display">\[
\begin{aligned}
0&amp;=\sum_{i=1}^{n_A} (y_i-\hat{\mu}_A) \Rightarrow \sum_{i=1}^{n_A}y_i =n_A\hat{\mu}_A \Rightarrow \frac{\sum_{i=1}^{n_A}y_i}{n_A} =\hat{\mu}_A\\
0&amp;= \sum_{i=n_A+1}^{n_A+n_B}  (y_i-\hat{\mu}_B) \Rightarrow \sum_{i=n_A+1}^{n_A+n_B}y_i =n_B\hat{\mu}_B \Rightarrow \frac{\sum_{i=n_A+1}^{n_A+n_B}y_i}{n_B} =\hat{\mu}_B.
\end{aligned}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-comptage-taux_imperfection" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-comptage-taux_imperfection"><span class="header-section-number">6.4</span> Taux d’imperfection</h2>
<p>Cet exercice est tiré de Agresti (2013).</p>
<p>Dans une expérience, on s’intéresse au taux d’imperfection pour deux procédés utilisés pour fabriquer des plaquettes de silicium dans des puces électroniques. Le traitement A a été appliqué pour dix plaquettes et les nombres d’imperfections sont <span class="math display">\[
8, 7, 6, 6, 3, 4, 7, 2, 3, 4.
\]</span> Le traitement B a été appliqué sur dix autres plaquettes et les nombres d’imperfections sont <span class="math display">\[
9, 9, 8, 14, 8, 13, 11, 5, 7, 6.
\]</span> On traite les données de comptage comme des variables Poisson indépendantes, avec moyennes <span class="math inline">\(\mu_A\)</span> et <span class="math inline">\(\mu_B\)</span>.</p>
<p><strong>a)</strong> Ajuster le modèle <span class="math display">\[\log(\mu_i)=\beta_0+\beta_1 x_i,\]</span> où <span class="math display">\[x_i=\left\{\begin{array}{ll} 0, &amp; \text{ si traitement A},\\ 1, &amp; \text{ si traitement B}.\\ \end{array}\right. \]</span> Montrer que <span class="math inline">\(\exp(\beta_1)=\mu_B/\mu_A\)</span> et interpréter la valeur de l’estimateur du paramètre.</p>
<p><strong>b)</strong> Tester <span class="math inline">\(H_0: \mu_A = \mu_B\)</span> avec le test de Wald. Iterpréter.</p>
<p><strong>c)</strong> Construire un intervalle de confiance à 95 % pour <span class="math inline">\(\mu_B/\mu_A\)</span>.</p>
<p><strong>d)</strong> Y a-t-il présence de surdispersion? Expliquer.</p>
<p><strong>e)</strong> Ajuster le modèle Binomiale Négative avec lien logarithmique. Que peut-on remarquer?</p>
<p><strong>f)</strong> Ajuster les modèles Poisson et Binomiale Négative aux 20 données sans inclure la variable explicative <span class="math inline">\(x\)</span>. Comparer les résultats et comparer les intervalles de confiance pour la moyenne de la variable réponse. Commenter.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Avec ce modèle, on a que <span class="math display">\[
\begin{aligned} \mu_A &amp;= \exp(\beta_0)\\ \mu_B &amp;= \exp(\beta_0+\beta_1)=\mu_A \exp(\beta_1), \end{aligned}
\]</span> ce qui implique que <span class="math inline">\(\exp(\beta_1)=\mu_B/\mu_A\)</span>. On ajuste le modèle en R, et on vérifie que cela est bien vrai :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">8</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">9</span>,<span class="dv">9</span>,<span class="dv">8</span>,<span class="dv">14</span>,<span class="dv">8</span>,<span class="dv">13</span>,<span class="dv">11</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">6</span>) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,<span class="at">each=</span><span class="dv">10</span>) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x,<span class="at">family=</span>poisson) </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ x, family = poisson)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.6094     0.1414  11.380  &lt; 2e-16 ***
x             0.5878     0.1764   3.332 0.000861 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 27.857  on 19  degrees of freedom
Residual deviance: 16.268  on 18  degrees of freedom
AIC: 94.349

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fu">mean</span>(y[<span class="fu">which</span>(x<span class="sc">==</span><span class="dv">1</span>)])<span class="sc">/</span><span class="fu">mean</span>(y[<span class="fu">which</span>(x<span class="sc">==</span><span class="dv">0</span>)])) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5877867</code></pre>
</div>
</div>
<p><strong>b)</strong> Puisque <span class="math inline">\(\exp(\beta_1)=\mu_B/\mu_A\)</span>, alors si <span class="math inline">\(H_0~: \mu_A=\mu_B\)</span> est vraie, <span class="math inline">\(\beta_1=0\)</span>. On peut utiliser la statistique de Wald directement, on trouve que le seuil observé du test est 0.000861. On rejette donc l’hypothèse nulle à un niveau de confiance de 99 %, ce qui implique que les moyennes diffèrent de façon significative.</p>
<p><strong>c)</strong> Un I.C. à 95 % pour <span class="math inline">\(\beta_1\)</span> est</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit1<span class="sc">$</span>coef[<span class="dv">2</span>]<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">summary</span>(fit1)<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="dv">2</span>]</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2420820 0.9334913</code></pre>
</div>
</div>
<p>Alors, un I.C. pour <span class="math inline">\(\mu_B/\mu_A\)</span> est <span class="math inline">\((\exp(0.2421),\exp(0.93349))=(1.273899 , 2.543373)\)</span>.</p>
<p><strong>d)</strong> Il n’y a pas d’indications de surdispersion, puisque la déviance est 16.26 sur 18 degrés de liberté, et <span class="math inline">\(16.26/18&lt;1\)</span>.</p>
<p><strong>e)</strong> Quand on ajuste une binomiale négative à ces données, on trouve que <span class="math inline">\(\theta_z\)</span> tend vers l’infini, donc le modèle Poisson est une simplification adéquate du modèle NB. En fait, les estimations des paramètres <span class="math inline">\(\beta_0\)</span> et <span class="math inline">\(\beta_1\)</span> sont exactement les mêmes que celles obtenues dans le modèle Poisson.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MASS' was built under R version 4.5.3</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(y<span class="sc">~</span>x) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace =
control$trace &gt; : iteration limit reached</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace =
control$trace &gt; : iteration limit reached</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = y ~ x, init.theta = 113420.3107, link = log)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.6094     0.1414  11.380  &lt; 2e-16 ***
x             0.5878     0.1764   3.332 0.000861 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(113420.3) family taken to be 1)

    Null deviance: 27.855  on 19  degrees of freedom
Residual deviance: 16.267  on 18  degrees of freedom
AIC: 96.349

Number of Fisher Scoring iterations: 1

              Theta:  113420 
          Std. Err.:  4076965 
Warning while fitting theta: iteration limit reached 

 2 x log-likelihood:  -90.349 </code></pre>
</div>
</div>
<p><strong>f)</strong> Dans ce cas, on remarque que, bien que l’estimation du paramètre est égale pour les deux modèles, l’écart-type diffère. Aussi, le modèle de Poisson ne semble plus adéquat, car <span class="math inline">\(Deviance/dl=27.857/19&gt;1\)</span>, alors que le modèle NB s’ajuste bien aux données. Cela montre que lorsqu’une variable explicative importante n’est pas observée, le modèle de Poisson peut perdre sa validité pour des données de comptage. La variable explicative manquante introduit de la surdispersion dans les données, ce qui est capturé efficacement avec la loi NB.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="dv">1</span>,<span class="at">family=</span>poisson) </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(y <span class="sc">~</span> <span class="dv">1</span>) </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ 1, family = poisson)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.94591    0.08451   23.02   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 27.857  on 19  degrees of freedom
Residual deviance: 27.857  on 19  degrees of freedom
AIC: 103.94

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit4) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = y ~ 1, init.theta = 18.2073559, link = log)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.94591    0.09944   19.57   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(18.2074) family taken to be 1)

    Null deviance: 20.279  on 19  degrees of freedom
Residual deviance: 20.279  on 19  degrees of freedom
AIC: 104.77

Number of Fisher Scoring iterations: 1

              Theta:  18.2 
          Std. Err.:  21.0 

 2 x log-likelihood:  -100.767 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(fit3<span class="sc">$</span>coef[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">summary</span>(fit3)<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="dv">2</span>]) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.931421 8.261090</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(fit4<span class="sc">$</span>coef[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">summary</span>(fit4)<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="dv">2</span>]) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.760386 8.506374</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-comptage-berkeley_admission" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-comptage-berkeley_admission"><span class="header-section-number">6.5</span> Admission à l’Université Berkeley</h2>
<p>Le tableau suivant dénombre les applications aux études graduées à l’Université Berkeley en Californie, pour l’automne 1973. On y voit les décisions d’admission par sexe et par département.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'knitr' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Données pour l'exercice sur les admissions aux études graduées. Source: P. Bickel et al. (1975). Science 187: 398-403.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Hommes
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Femmes
</div></th>
</tr>
<tr class="even">
<th style="text-align: center;" data-quarto-table-cell-role="th">Département</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Admis</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Non admis</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Admis</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Non admis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">512</td>
<td style="text-align: center;">313</td>
<td style="text-align: center;">89</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">353</td>
<td style="text-align: center;">207</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">205</td>
<td style="text-align: center;">202</td>
<td style="text-align: center;">391</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">138</td>
<td style="text-align: center;">279</td>
<td style="text-align: center;">131</td>
<td style="text-align: center;">244</td>
</tr>
<tr class="odd">
<td style="text-align: center;">E</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">138</td>
<td style="text-align: center;">94</td>
<td style="text-align: center;">299</td>
</tr>
<tr class="even">
<td style="text-align: center;">F</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">351</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">317</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a)</strong> Effectuer une régression Poisson avec lien canonique sur le nombre de personnes admises, en utilisant le logarithme du nombre total de personnes qui ont appliqué comme terme offset. Si on utilise seulement le sexe comme variable explicative, est-ce que le sexe a un impact significatif sur le taux d’acceptation?</p>
<p><strong>b)</strong> Si on ajoute le département comme variable explicative dans le modèle en a), est-ce que le sexe a toujours un impact significatif sur le taux d’acceptation? Qu’est-ce que cela signifie?</p>
<p><strong>c)</strong> Est-ce que l’intéraction entre le sexe et le département est une variable significative dans le modèle? Que peut-on conclure?</p>
<p><strong>d)</strong> Est-ce que le modèle Poisson est adéquat pour ces données? Utiliser la déviance et la statistique de Pearson.</p>
<p><strong>e)</strong> Refaire les questions a) à c) en utilisant un modèle binomial avec lien logistique, en supposant que <span class="math inline">\(m_i\)</span> est le nombre total de personnes qui ont appliqué.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> On y va</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,<span class="at">each=</span><span class="dv">6</span>) </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>Dep <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span>) </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">512</span>,<span class="dv">353</span>,<span class="dv">120</span>,<span class="dv">138</span>,<span class="dv">53</span>,<span class="dv">22</span>,<span class="dv">89</span>,<span class="dv">17</span>,<span class="dv">202</span>,<span class="dv">131</span>,<span class="dv">94</span>,<span class="dv">24</span>) </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>no <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">313</span>,<span class="dv">207</span>,<span class="dv">205</span>,<span class="dv">279</span>,<span class="dv">138</span>,<span class="dv">351</span>,<span class="dv">19</span>,<span class="dv">8</span>,<span class="dv">391</span>,<span class="dv">244</span>,<span class="dv">299</span>,<span class="dv">317</span>) </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> y<span class="sc">+</span>no </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>fitpSex <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">factor</span>(sex)<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(nb)),<span class="at">family=</span>poisson) </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitpSex) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ factor(sex) + offset(log(nb)), family = poisson)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.80926    0.02889 -28.011  &lt; 2e-16 ***
factor(sex)1 -0.38298    0.05128  -7.468 8.15e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 551.69  on 11  degrees of freedom
Residual deviance: 493.56  on 10  degrees of freedom
AIC: 573.76

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>On trouve donc que la valeur-<span class="math inline">\(p\)</span> du test de Wald <span class="math inline">\(H_0~: \beta^{SEX}=0\)</span> est <span class="math inline">\(8.15\times10^{-14}\)</span> ce qui est hautement significatif. Puisque le coefficient est négatif et que le niveau de base utilisé est <code>hommes</code>, cela signifie que les femmes ont moins de chance d’être acceptées aux études graduées que les hommes.</p>
<p><strong>b)</strong> On ajoute le département:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fitp2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">factor</span>(sex)<span class="sc">+</span><span class="fu">factor</span>(Dep)<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(nb)),<span class="at">family=</span>poisson) </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitp2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ factor(sex) + factor(Dep) + offset(log(nb)), 
    family = poisson)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.44677    0.04148 -10.771   &lt;2e-16 ***
factor(sex)1  0.05859    0.06166   0.950    0.342    
factor(Dep)1 -0.01391    0.06625  -0.210    0.834    
factor(Dep)2 -0.63911    0.07660  -8.344   &lt;2e-16 ***
factor(Dep)3 -0.66125    0.07675  -8.615   &lt;2e-16 ***
factor(Dep)4 -0.97250    0.09836  -9.887   &lt;2e-16 ***
factor(Dep)5 -2.32388    0.15468 -15.024   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 551.6926  on 11  degrees of freedom
Residual deviance:   6.6698  on  5  degrees of freedom
AIC: 96.868

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>Dans ce modèle, le résultat du test de Wald pour le coefficient de la variable Sexe est différent. Puisque le seuil observé du test est 34.5 %, on ne peut pas rejeter l’hypothèse nulle que <span class="math inline">\(\beta^{SEX}=0\)</span>. Cela signifie que le sexe n’est pas un facteur qui influence le taux d’admission aux études graduées lorsqu’on prend en considération le département. Il en est ainsi car les femmes appliquent plus souvent que les hommes dans des départements où il est plus difficile d’être admis.</p>
<p><strong>c)</strong> À l’aide de l’analyse de la déviance, on trouve que l’interaction n’est pas significative : <span class="math display">\[
\Delta Deviance = 6.67 &lt; \chi^2 (0.95,5) = 11.07.
\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fitp <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">factor</span>(sex)<span class="sc">*</span><span class="fu">factor</span>(Dep)<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(nb)),<span class="at">family=</span>poisson) </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fitp) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: poisson, link: log

Response: y

Terms added sequentially (first to last)

                        Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                                       11     551.69              
factor(sex)              1    58.13        10     493.56  2.45e-14 ***
factor(Dep)              5   486.89         5       6.67 &lt; 2.2e-16 ***
factor(sex):factor(Dep)  5     6.67         0       0.00    0.2464    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">5</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.0705</code></pre>
</div>
</div>
<p><strong>d)</strong> Le modèle final est celui avec une seule variable explicative dichotomique: le département. La déviance pour ce modèle est 7.5706, ce qui est légèrement supérieur à 6, le nombre de degrés de liberté. Toutefois, puisque <span class="math inline">\(Deviance/dl\approx1.26\)</span>, cela n’est pas très alarmant, et il n’y a pas de raison de supposer que le modèle de Poisson est inadéquat. La statistique de Pearson est 8.03, ce qui est aussi une valeur attendue pour la loi chi-carrée avec 6 degrés de liberté.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fitpDep <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">factor</span>(Dep)<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(nb)),<span class="at">family=</span>poisson) </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitpDep) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ factor(Dep) + offset(log(nb)), family = poisson)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.43981    0.04079 -10.782   &lt;2e-16 ***
factor(Dep)1 -0.01830    0.06608  -0.277    0.782    
factor(Dep)2 -0.60784    0.06906  -8.801   &lt;2e-16 ***
factor(Dep)3 -0.64004    0.07336  -8.725   &lt;2e-16 ***
factor(Dep)4 -0.93966    0.09201 -10.212   &lt;2e-16 ***
factor(Dep)5 -2.30243    0.15298 -15.050   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 551.6926  on 11  degrees of freedom
Residual deviance:   7.5706  on  6  degrees of freedom
AIC: 95.769

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((y<span class="sc">-</span><span class="fu">fitted</span>(fitpDep))<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">fitted</span>(fitpDep)) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.025236</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">8.025236</span>,<span class="dv">6</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7637397</code></pre>
</div>
</div>
<p><strong>e)</strong> On recommence et on obtient exactement les mêmes conclusions:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fitbSex <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y,nb<span class="sc">-</span>y) <span class="sc">~</span> <span class="fu">factor</span>(sex),<span class="at">family=</span>binomial) </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitbSex) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(y, nb - y) ~ factor(sex), family = binomial)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.22013    0.03879  -5.675 1.38e-08 ***
factor(sex)1 -0.61035    0.06389  -9.553  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 877.06  on 11  degrees of freedom
Residual deviance: 783.61  on 10  degrees of freedom
AIC: 856.55

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>fitb2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y,nb<span class="sc">-</span>y) <span class="sc">~</span> <span class="fu">factor</span>(sex)<span class="sc">+</span><span class="fu">factor</span>(Dep),<span class="at">family=</span>binomial) </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitb2) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(y, nb - y) ~ factor(sex) + factor(Dep), family = binomial)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.58205    0.06899   8.436   &lt;2e-16 ***
factor(sex)1  0.09987    0.08085   1.235    0.217    
factor(Dep)1 -0.04340    0.10984  -0.395    0.693    
factor(Dep)2 -1.26260    0.10663 -11.841   &lt;2e-16 ***
factor(Dep)3 -1.29461    0.10582 -12.234   &lt;2e-16 ***
factor(Dep)4 -1.73931    0.12611 -13.792   &lt;2e-16 ***
factor(Dep)5 -3.30648    0.16998 -19.452   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 877.056  on 11  degrees of freedom
Residual deviance:  20.204  on  5  degrees of freedom
AIC: 103.14

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>fitb <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y,nb<span class="sc">-</span>y) <span class="sc">~</span> <span class="fu">factor</span>(sex)<span class="sc">*</span><span class="fu">factor</span>(Dep),<span class="at">family=</span>binomial) </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fitb) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: cbind(y, nb - y)

Terms added sequentially (first to last)

                        Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                                       11     877.06              
factor(sex)              1    93.45        10     783.61 &lt; 2.2e-16 ***
factor(Dep)              5   763.40         5      20.20 &lt; 2.2e-16 ***
factor(sex):factor(Dep)  5    20.20         0       0.00  0.001144 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">5</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.0705</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-comptage-deces_cancer_poumon" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-comptage-deces_cancer_poumon"><span class="header-section-number">6.6</span> Décès dus au cancer du poumon</h2>
<p>Le fichier de données <code>MNLung.csv</code> (séparé avec des virgules) contient des données sur le nombre de décès dus au cancer du poumon dans 87 régions au Minnesota, pour les hommes et les femmes. L’objectif de l’étude pour laquelle les données ont été recueillies était d’examiner si l’exposition au gaz radon est relié à un changement dans le taux de morbidité standardisé. La base de données contient sept colonnes:</p>
<ul>
<li><p><code>County</code>: Nom de la région;</p></li>
<li><p><code>ID</code>: Numéro d’identifcation de la région dans la base de données;</p></li>
<li><p><code>YM</code>: Nombre de décès dûs au cancer du poumon chez les hommes sur une période de 5 ans;</p></li>
<li><p><code>EM</code>: Espérance du nombre de cas YM, basé sur des facteurs démographiques;</p></li>
<li><p><code>YF</code>: Nombre de décès dûs au cancer du poumon chez les femmes sur une période de 5 ans;</p></li>
<li><p><code>EF</code>: Espérance du nombre de cas YF, basé sur des facteurs démographiques;</p></li>
<li><p><code>Radon</code>: Mesure moyenne de l’exposition au radon dans chaque région pour la période de 5 ans.</p></li>
</ul>
<p>Le taux de morbidité standardisé (SMR) pour la région <span class="math inline">\(i\)</span> est défini comme <span class="math display">\[SMR_i=\frac{Y_i}{E_i}.\]</span> En utilisant un modèle linéaire généralisé Poisson approprié, répondre aux question suivantes :</p>
<p><strong>a)</strong> Y a-t-il des preuves dans ces données que le radon est associé avec un changement dans le SMR ?</p>
<p><strong>b)</strong> Y a-t-il une différence entre le SMR pour les hommes et les femmes, lorsque l’on inclut ou pas la variable explicative radon dans le modèle?</p>
<p><strong>c)</strong> Donner les prévisions pour le SMR, avec la mesure d’incertitude, pour des hommes dans une région hypothétique où l’exposition moyenne au radon est de 6 unités.</p>
<p><strong>d)</strong> Commenter sur la validité du modèle de Poisson pour ces données.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Si <span class="math inline">\(Y_{i}\sim Poisson(E_{i}\lambda_{i})\)</span>, le lien canonique est <span class="math display">\[
\log(\mu_{i})=log(E_{i})+log(\lambda_{i}),
\]</span> où <span class="math inline">\(\lambda_{i}\)</span> est la moyenne <span class="math inline">\(SMR\)</span> pour l’observation <span class="math inline">\(i\)</span>. <span class="math inline">\(\log(E_{i})\)</span>, le logarithme naturel du nombre espéré de cancers des poumons est basé sur les données démographiques du comté, est passé à la fonction <code>glm</code> comme un <code>offset</code>. Les données pour les hommes et les femmes sont combinées pour créer un modèle à une seule variable explicative numérique, l’exposition au radon, et une valeriable explicative catégorielle binaire, le sexe (0 pour les hommes et 1 pour les femmes).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>Ytot <span class="ot">&lt;-</span> <span class="fu">c</span>(YM,YF) </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>Etot <span class="ot">&lt;-</span> <span class="fu">c</span>(EM,EF) </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>Sex <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">length</span>(YM)),<span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">length</span>(YF))) <span class="do">## 1 si femme </span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>Radontot <span class="ot">&lt;-</span> <span class="fu">rep</span>(Radon,<span class="dv">2</span>) </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>modsex <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Sex<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>modsexrad <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Radontot<span class="sc">+</span>Sex<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modsex,modsexrad) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Ytot ~ Sex + offset(log(Etot))
Model 2: Ytot ~ Radontot + Sex + offset(log(Etot))
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       172     410.27                          
2       171     364.05  1    46.22 1.057e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.99</span>,<span class="dv">1</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.634897</code></pre>
</div>
</div>
<p>Comme vu ci-haut, l’analyse de déviance montre que l’exposition au radon influence le nombre de cancers du poumon dans un comté particulier :</p>
<p><span class="math display">\[
\begin{aligned} \Delta Deviance = 46.22 &gt; \chi^{2}_{(1;0.99)}=6.6349. \end{aligned}
\]</span></p>
<p><strong>b)</strong> Le modèle nul et le modèle avec la variable explicative sexe sont ajustés.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>modtot <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>modsex <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Sex<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modtot,modsex) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Ytot ~ 1 + offset(log(Etot))
Model 2: Ytot ~ Sex + offset(log(Etot))
  Resid. Df Resid. Dev Df  Deviance Pr(&gt;Chi)
1       173     410.28                      
2       172     410.27  1 0.0093398    0.923</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">1</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.841459</code></pre>
</div>
</div>
<p>L’analyse de déviance montre que <span class="math inline">\(\Delta Deviance= 0.0093398&lt;\chi^{2}_{(1;0.95)}=3.8415\)</span>. Alors, le modèle nul est une simplification appropriée du modèle avec le sexe, donc cette variable n’est pas significative.</p>
<p>Cependant, l’analyse de déviance en R est montrée ci-bas quand la variable d’exposition au Radon est incluse dans le modèle. Si on considère d’abord le modèle avec les effets principaux et les interactions, on trouve <span class="math inline">\(\Delta Deviance= 8.823&gt;\chi^{2}_{(1;0.99)}\)</span>, ce qui signifie que le modèle avec les effets principaux est seulement une simplification adéquate du modèle qui inclut aussi les interactions. Ainsi, la variable catégorielle Sex est significative sans le modèle via son interaction avec l’exposition au radon. On note que, même si l’effet principal du sexe ne semble pas significatif, il est gardé par convention.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>modtotrad <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Radontot<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>modsexrad <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Radontot<span class="sc">+</span>Sex<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>modsexradINT <span class="ot">&lt;-</span> <span class="fu">glm</span>(Ytot <span class="sc">~</span> Radontot<span class="sc">*</span>Sex<span class="sc">+</span><span class="fu">offset</span>(<span class="fu">log</span>(Etot)),<span class="at">family=</span>poisson) </span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modtot,modtotrad,modsexrad,modsexradINT) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Ytot ~ 1 + offset(log(Etot))
Model 2: Ytot ~ Radontot + offset(log(Etot))
Model 3: Ytot ~ Radontot + Sex + offset(log(Etot))
Model 4: Ytot ~ Radontot * Sex + offset(log(Etot))
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       173     410.28                          
2       172     364.06  1   46.219 1.058e-11 ***
3       171     364.05  1    0.011  0.917333    
4       170     355.23  1    8.823  0.002975 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>c)</strong> Les prévisions sont obtenues avec la commande</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modsexradINT,</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">data.frame</span>(<span class="at">Radontot=</span><span class="dv">6</span>,<span class="at">Sex=</span><span class="dv">0</span>,<span class="at">Etot=</span><span class="dv">1</span>),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">type=</span><span class="st">"response"</span>,<span class="at">se.fit=</span><span class="cn">TRUE</span>) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Si le modèle <code>Sex*Radon</code> est utilisé, on trouve <span class="math display">\[\hat{SMR}_{Sex=0,Radon=6}=0.9708183,\]</span> avec écart-type 0.01415307.</p>
<p><strong>d)</strong> Le modèle <code>Sex*Radon</code> a une déviance de 355.23 sur 170 degrés de liberté. Une méthode heuristrique de valider le modèle est d’estimer son paramètre de dispersion <span class="math display">\[\hat{\phi}=\frac{355.23}{170}=2.089\]</span> et de le comparer avec 1, le paramètre de dispersion implicite dans un modèle Poisson vu sa paramétrisation avec la famille exponentielle linéaire. Ce diagnostic suggère qu’il y a présence de surdispersion dans les données comme <span class="math inline">\(\hat{\phi}\)</span> est plus grand que 1. Ajuster un modèle quasi-Poisson mènrait à la même conclusion : le paramètre de dispersion estimé est 1.98311, plus près de 2. Ainsi, on peut conclure que le modèle Poisson n’est pas adéquat. On pourrait plutôt considérer un modèle binomial négatif pour capturer cette surdispersion.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapitres/glm.html" class="pagination-link" aria-label="Modèles linéaires généralisés (GLM)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapitres/binom.html" class="pagination-link" aria-label="Modélisation de données binomiales">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>