<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Modèles linéaires généralisés (GLM) – ACT2003 — Recueil d'exercices</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapitres/comptage.html" rel="next">
<link href="../chapitres/selection.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a522afb83bf8ae494942cf1b0ac9d4c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    macros: {
      esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      ex:     "\\mathbb{E}",
      var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      vr:     "\\mathrm{Var}",
      prob:   "\\Pr",
      Prob:   "\\Pr",
      cov:    ["\\mathrm{Cov}\\!\\left(#1\\right)",1],
      Cov:    "\\mathrm{Cov}",
      SST:    "\\mathrm{SST}",
      SSR:    "\\mathrm{SSR}",
      SSE:    "\\mathrm{SSE}",
      MSE:    "\\mathrm{MSE}",
      MSR:    "\\mathrm{MSR}",
      d:      "\\mathrm{d}",
      bm:     ["\\boldsymbol{#1}", 1],
      yvec:   "\\mathbf{Y}",
      xvec:   "\\mathbf{x}",
      Xmat:   "\\mathbf{X}",
      betavec: "\\boldsymbol{\\beta}",
      epsvec: "\\boldsymbol{\\varepsilon}",
      mat:    ["\\mathbf{#1}", 1],
      varmat:    ["\\mathbf{V} ( #1 )", 1],
      hatbetavec: "\\boldsymbol{\\hat{\\beta}}",
      hatepsvec: "\\boldsymbol{\\hat{\\varepsilon}}",
      Norm: "\\mathcal{N}",
      diag: "\\mathrm{diag}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/glm.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACT2003 — Recueil d’exercices</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/simple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Régression linéaire simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Régression linéaire multiple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sélection de modèle et régression régularisée</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/glm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/comptage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modélisation de données binomiales</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sec-glm-famille_expo_lineaire" id="toc-sec-glm-famille_expo_lineaire" class="nav-link active" data-scroll-target="#sec-glm-famille_expo_lineaire"><span class="header-section-number">5.1</span> Famille exponentielle linéaire</a></li>
  <li><a href="#sec-glm-lien_poisson" id="toc-sec-glm-lien_poisson" class="nav-link" data-scroll-target="#sec-glm-lien_poisson"><span class="header-section-number">5.2</span> Fonctions de lien avec une loi de Poisson</a></li>
  <li><a href="#sec-glm-lien_gamma" id="toc-sec-glm-lien_gamma" class="nav-link" data-scroll-target="#sec-glm-lien_gamma"><span class="header-section-number">5.3</span> Fonctions de lien avec une loi gamma</a></li>
  <li><a href="#sec-glm-glm_poisson_univarie" id="toc-sec-glm-glm_poisson_univarie" class="nav-link" data-scroll-target="#sec-glm-glm_poisson_univarie"><span class="header-section-number">5.4</span> GLM Poisson univarié</a></li>
  <li><a href="#sec-glm-deviance_binomiale" id="toc-sec-glm-deviance_binomiale" class="nav-link" data-scroll-target="#sec-glm-deviance_binomiale"><span class="header-section-number">5.5</span> Déviance du modèle binomial</a></li>
  <li><a href="#sec-glm-residus_gamma" id="toc-sec-glm-residus_gamma" class="nav-link" data-scroll-target="#sec-glm-residus_gamma"><span class="header-section-number">5.6</span> Résidus pour la loi gamma</a></li>
  <li><a href="#sec-glm-tests_resistance" id="toc-sec-glm-tests_resistance" class="nav-link" data-scroll-target="#sec-glm-tests_resistance"><span class="header-section-number">5.7</span> Tests de résistance</a></li>
  <li><a href="#sec-glm-sinistres_auto_royaume_uni" id="toc-sec-glm-sinistres_auto_royaume_uni" class="nav-link" data-scroll-target="#sec-glm-sinistres_auto_royaume_uni"><span class="header-section-number">5.8</span> Sinistres automobiles au Royaume-Uni</a></li>
  <li><a href="#sec-glm-turbines_fissurees" id="toc-sec-glm-turbines_fissurees" class="nav-link" data-scroll-target="#sec-glm-turbines_fissurees"><span class="header-section-number">5.9</span> Nombre de turbines fissurées</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/simple.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/glm.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèles linéaires généralisés (GLM)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="sec-glm-famille_expo_lineaire" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-glm-famille_expo_lineaire"><span class="header-section-number">5.1</span> Famille exponentielle linéaire</h2>
<p>Est-ce que les distributions suivantes font partie de la famille exponentielle linéaire? Si oui, écrire la densité sous la forme exponentielle linéaire, donner le paramètre canonique, le paramètre de dispersion, l’espérance et la variance de <span class="math inline">\(Y\)</span> en termes de la fonction <span class="math inline">\(b()\)</span> et la relation <span class="math inline">\(V()\)</span> entre la moyenne et la variance.</p>
<p><strong>a)</strong> Normale<span class="math inline">\((\mu,\sigma^2)\)</span></p>
<p><strong>b)</strong> Uniforme<span class="math inline">\((0,\beta)\)</span></p>
<p><strong>c)</strong> Poisson<span class="math inline">\((\lambda)\)</span></p>
<p><strong>d)</strong> Bernoulli<span class="math inline">\((\pi)\)</span></p>
<p><strong>e)</strong> Binomiale<span class="math inline">\((m, \pi)\)</span>, <span class="math inline">\(m&gt;0\)</span> est un entier et est connu (On considère <span class="math inline">\(Y^*=Y/m\)</span>).</p>
<p><strong>f)</strong> Pareto<span class="math inline">\((\alpha,\lambda)\)</span></p>
<p><strong>g)</strong> Gamma<span class="math inline">\((\alpha,\beta)\)</span></p>
<p><strong>h)</strong> Binomiale négative<span class="math inline">\((r,\pi)\)</span> avec <span class="math inline">\(r\)</span> connu (On considère <span class="math inline">\(Y^*=Y/r\)</span>).</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong></p>
<p><span class="math display">\[\begin{align*}
f_{Y}(y)&amp;=\frac{1}{(2\pi\sigma^2)^1/2}\exp\left(-\frac{(y-\mu)^2}{2\sigma^2}\right),\, y\in\mathbb{R}\\
&amp;=\exp\left(\frac{y\mu-\mu^2/2}{\sigma^2}-\frac{y^2}{2\sigma^2}-\frac{\ln(2\pi\sigma^2)}{2}\right),\, y\in\mathbb{R}.
\end{align*}\]</span></p>
<ul>
<li><p>Paramètre canonique: <span class="math inline">\(\theta=\mu\)</span></p></li>
<li><p>Paramètre de dispersion: <span class="math inline">\(\phi=\sigma^2\)</span></p></li>
<li><p><span class="math inline">\(b(\theta)=\frac{\theta^2}{2}\)</span></p></li>
<li><p><span class="math inline">\(\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\frac{\theta^2}{2}=\theta=\mu\)</span></p></li>
<li><p><span class="math inline">\(\var{Y}=\phi\ddot{b}(\theta)=\sigma^2\frac{\partial}{\partial\theta}\theta=\sigma^2\)</span></p></li>
<li><p><span class="math inline">\(V(\mu)=1\)</span>.</p></li>
</ul>
<p><strong>b)</strong> Uniforme<span class="math inline">\((0,\beta)\)</span>: non. Le domaine dépend du paramètre <span class="math inline">\(\beta\)</span>.</p>
<p><strong>c)</strong> Poisson<span class="math inline">\((\lambda)\)</span> : <span class="math display">\[
\begin{aligned}
f_{Y}(y;\lambda)&amp;=\frac{\lambda^{y}e^{-\lambda}}{y!} \text{, pour }y\in \mathbb{N}^{+}\\
&amp;=\exp\{y\ln \lambda - \lambda - \ln y!\}\\
f_{Y}(y;\theta,\phi)&amp;=\exp\left\{\frac{y\theta - e^{\theta}}{\phi} - \ln y!\right\}.
\end{aligned}
\]</span></p>
<ul>
<li><p>Paramètre canonique: <span class="math inline">\(\theta=\ln \lambda\)</span></p></li>
<li><p>Paramètre de dispersion: <span class="math inline">\(\phi=1\)</span></p></li>
<li><p><span class="math inline">\(b(\theta)=e^{\theta}\)</span></p></li>
<li><p><span class="math inline">\(\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}e^{\theta}=e^{\theta}=\lambda\)</span></p></li>
<li><p><span class="math inline">\(\var{Y}=\phi\ddot{b}(\theta)=\frac{\partial}{\partial\theta}e^{\theta}=e^{\theta}=\lambda\)</span></p></li>
<li><p><span class="math inline">\(V(\mu)=\mu\)</span>.</p></li>
</ul>
<p><strong>d)</strong> Bernoulli<span class="math inline">\((\pi)\)</span> <span class="math display">\[
\begin{aligned}
f_{Y}(y;\pi)&amp;=\pi^{y}(1-\pi)^{1-y}1(y \in \{0,1\})\\
&amp;=\exp\left\{y\ln\left(\frac{\pi}{1-\pi}\right)+\ln(1-\pi)\right\}1(y \in \{0,1\}).\\
\end{aligned}
\]</span></p>
<ul>
<li><p>Paramètre canonique: <span class="math inline">\(\theta=\ln\left(\frac{\pi}{1-\pi}\right)\)</span></p></li>
<li><p>Paramètre de dispersion: <span class="math inline">\(\phi=1\)</span></p></li>
<li><p><span class="math inline">\(b(\theta)=\ln(1+e^{\theta})\)</span></p></li>
<li><p><span class="math inline">\(\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\ln(1+e^{\theta})=\frac{e^{\theta}}{1+e^\theta}=\pi\)</span></p></li>
<li><p><span class="math inline">\(\var{Y}=\phi\ddot{b}(\theta)=\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1+e^\theta}=\frac{e^\theta}{(1+e^\theta)^2}=\pi(1-\pi)\)</span></p></li>
<li><p><span class="math inline">\(V(\mu)=\mu(1-\mu)\)</span>.</p></li>
</ul>
<p><strong>e)</strong> Binomiale<span class="math inline">\((m, \pi)\)</span>, <span class="math inline">\(m&gt;0\)</span> est un entier et est connu. <span class="math display">\[
\begin{aligned}
f_{Y}(y;\pi)&amp;=\begin{pmatrix} m\\y\end{pmatrix}\pi^{y}(1-\pi)^{m-y}1(y \in \{0,1,...,m\})\\
&amp;=\exp\left\{y\ln\left(\frac{\pi}{1-\pi}\right)+m\ln(1-\pi)+\ln\begin{pmatrix} m\\y\end{pmatrix}\right\}1(y \in \{0,1,...,m\}).\\
\end{aligned}
\]</span> Dans cette représentation, on a <span class="math display">\[\esp{Y}=m\pi \text{ et } \var{Y}=m\pi(1-\pi).\]</span> Cette forme est moins utilisée car l’espérance de <span class="math inline">\(Y\)</span> dépend de <span class="math inline">\(m\)</span>, le paramètre de dispersion. Souvent, on transforme les données. On utilise plutôt <span class="math inline">\(Y^{*}=Y/m\)</span>. Alors, pour ces données transformées, <span class="math display">\[
\begin{aligned}
f_{Y^{*}}(y;\pi)&amp;=\exp\left\{my\ln\left(\frac{\pi}{1-\pi}\right)+m\ln(1-\pi)+\ln\begin{pmatrix} m\\my\end{pmatrix}\right\},  y \in \{0,1/m,...,1\}\\
&amp;=\exp\left\{\frac{y\ln\left(\frac{\pi}{1-\pi}\right)+\ln(1-\pi)}{1/m}+\ln\begin{pmatrix} m\\my\end{pmatrix}\right\},  y \in \{0,1/m,...,1\}.\\
\end{aligned}
\]</span></p>
<ul>
<li><p>Paramètre canonique : <span class="math inline">\(\theta=\ln\left(\frac{\pi}{1-\pi}\right)\)</span></p></li>
<li><p>Paramètre de dispersion: <span class="math inline">\(\phi=1/m\)</span></p></li>
<li><p><span class="math inline">\(b(\theta)=\ln(1+e^{\theta})\)</span></p></li>
<li><p><span class="math inline">\(\esp{Y^*}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\ln(1+e^{\theta})=\frac{e^{\theta}}{1+e^\theta}=\pi\)</span></p></li>
<li><p><span class="math inline">\(\var{Y^*}=\phi\ddot{b}(\theta)=\frac{1}{m}\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1+e^\theta}=\frac{e^\theta}{m(1+e^\theta)^2}=\frac{\pi(1-\pi)}{m}\)</span></p></li>
<li><p><span class="math inline">\(V(\mu)=\mu(1-\mu)\)</span>.</p></li>
</ul>
<p><strong>f)</strong> Pareto<span class="math inline">\((\alpha,\lambda)\)</span>: non.</p>
<p><strong>g)</strong> Gamma<span class="math inline">\((\alpha,\beta)\)</span> Soit <span class="math inline">\(Y\sim Gamma(\alpha,\beta)\)</span>. Alors, avec un peu de travail, la densité peut être écrite sous la forme exponentielle linéaire.</p>
<p><span class="math display">\[
f_{Y}(y;\alpha,\beta)=\frac{\beta^{\alpha}}{\Gamma(\alpha)}y^{\alpha-1}e^{-\beta y},
\]</span> pour <span class="math inline">\(y&gt;0\)</span>. On reparamétrise: <span class="math inline">\(\mu=\alpha/\beta=\esp{Y}\)</span> et <span class="math inline">\(\alpha\)</span>, on a donc <span class="math inline">\(\beta=\alpha/\mu\)</span> et</p>
<p><span class="math display">\[
f_{Y}(y;\alpha,\mu)=\frac{1}{y\Gamma(\alpha)}\left(\frac{\alpha y}{\mu}\right)^{\alpha}\exp\left\{-\frac{\alpha y}{\mu}\right\}.
\]</span></p>
<p>Posons <span class="math inline">\(\theta=-1/\mu\)</span>, et <span class="math inline">\(a(\phi)=1/\alpha\)</span>, alors on trouve</p>
<p><span class="math display">\[
f_{Y}(y;\theta,\phi)=\exp\left\{\frac{y\theta +\ln(-\theta)}{\phi} +\alpha\ln\alpha+(\alpha-1)\ln y -\ln\Gamma(\alpha)\right\}.
\]</span></p>
<p>Donc, <span class="math inline">\(b(\theta)=-\ln(-\theta)\)</span> et <span class="math inline">\(a(\phi)=1/\alpha \Rightarrow \dot{b}(\theta)=\frac{-1}{\theta}=\mu\)</span> et <span class="math inline">\(\ddot{b}(\theta)=\frac{1}{\theta^{2}}=\mu^{2}\)</span>. Finalement, <span class="math display">\[
\esp{Y}=\frac{-1}{\theta}=\mu \text{ et } \var{Y}=\frac{1}{\alpha}\mu^{2}.
\]</span></p>
<p><strong>h)</strong> Binomiale négative<span class="math inline">\((r,\pi)\)</span> avec <span class="math inline">\(r\)</span> connu. On considère <span class="math inline">\(Y^*=Y/r\)</span>: <span class="math display">\[
\begin{aligned}
f_Y^*(y)&amp;=\begin{pmatrix} r+ry-1\\ry\end{pmatrix}\pi^r(1-\pi)^{ry}, \text{ pour } y\in \{0,\frac{1}{r},\frac{2}{r},...\}\\
&amp;=\exp\left(ry\ln(1-\pi)+r\ln\pi+\ln\begin{pmatrix} r+ry-1\\ry\end{pmatrix}\right).
\end{aligned}
\]</span></p>
<ul>
<li><p>Paramètre canonique: <span class="math inline">\(\theta=\ln(1-\pi)\)</span></p></li>
<li><p>Paramètre de dispersion: <span class="math inline">\(\phi=1/r\)</span></p></li>
<li><p><span class="math inline">\(b(\theta)=-\ln(1-e^\theta)\)</span></p></li>
<li><p><span class="math inline">\(\esp{Y^*}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}-\ln(1-e^\theta)=\frac{e^{\theta}}{1-e^\theta}=\frac{1-\pi}{\pi}\)</span></p></li>
<li><p><span class="math inline">\(\var{Y^*}=\phi\ddot{b}(\theta)=\frac{1}{r}\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1-e^\theta}=\frac{e^\theta}{r(1-e^\theta)^2}=\frac{(1-\pi)}{r\pi^2}\)</span></p></li>
<li><p><span class="math inline">\(V(\mu)=\mu(\mu+1)\)</span>.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="sec-glm-lien_poisson" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-glm-lien_poisson"><span class="header-section-number">5.2</span> Fonctions de lien avec une loi de Poisson</h2>
<p>Quelles fonctions de lien peut-on utiliser pour un GLM avec une loi de Poisson?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\eta=\ln(\mu)\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Le lien canonique est le lien log: <span class="math inline">\(\eta=\ln(\mu)\)</span>. On pourrait aussi utiliser d’autres fonctions de lien, telle que le lien identité <span class="math inline">\(\eta=\mu\)</span>, le lien inverse <span class="math inline">\(\eta=\frac{1}{\mu}\)</span>, mais le lien log est le plus approprié parce que son utilisation garantit une moyenne <span class="math inline">\(\mu\)</span> positive, ce qui est nécessaire pour la loi de Poisson.</p>
</div>
</div>
</div>
</section>
<section id="sec-glm-lien_gamma" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-glm-lien_gamma"><span class="header-section-number">5.3</span> Fonctions de lien avec une loi gamma</h2>
<p>Quel est le lien canonique pour la loi gamma? Est-ce que ce lien est toujours approprié?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\eta=1/\mu\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Le lien canonique pour la loi Gamma est le lien inverse <span class="math inline">\(\eta=1/\mu\)</span>. Comme la moyenne d’une loi Gamma est toujours positive, ce lien n’est pas toujours approprié parce qu’il ne restreint pas le domaine de <span class="math inline">\(\mu\)</span> aux réels positifs. Le lien log serait plus approprié dans certains cas.</p>
</div>
</div>
</div>
</section>
<section id="sec-glm-glm_poisson_univarie" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-glm-glm_poisson_univarie"><span class="header-section-number">5.4</span> GLM Poisson univarié</h2>
<p>On suppose que <span class="math inline">\(Y_1,...,Y_n\)</span> sont des v.a.s indépendantes et <span class="math inline">\(Y_i\sim Poisson(\mu_i)\)</span>. Pour chaque observation, on a une seule variable explicative <span class="math inline">\(x_i\)</span>.</p>
<p><strong>a)</strong> Quel est le lien canonique?</p>
<p><strong>b)</strong> Trouver les fonctions de score (à résoudre pour l’estimation des paramètres par maximum de vraisemblance)</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <span class="math inline">\(\eta=g(\mu)=\ln(\mu)\)</span></p>
<p><strong>b)</strong> <span class="math inline">\(\sum_{i=1}^n y_i-e^{\beta_0+\beta_1x_i}=0 \text{ et } \sum_{i=1}^n x_i(y_i-e^{\beta_0+\beta_1x_i})=0\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <span class="math inline">\(\eta=g(\mu)=\ln(\mu)\)</span></p>
<p><strong>b)</strong> On a <span class="math display">\[
\ln(\mu_i)=\eta_i=\beta_0+\beta_1x_i.
\]</span></p>
<p>La densité de la loi Poisson est <span class="math display">\[
\begin{aligned} f_{Y_i}(y_i;\mu_i)&amp;=\exp\left(y_i\ln\mu_i-\mu_i-\ln y_i!\right)\\ f_{Y_i}(y_i;\beta_0,\beta_1)&amp;=\exp\left(y_i(\beta_0+\beta_1x_i)-e^{\beta_0+\beta_1x_i}-\ln y_i!\right). \end{aligned}
\]</span></p>
<p>La fonction de vraisemblance et la log-vraisemblance sont donc :</p>
<p><span class="math display">\[
\begin{aligned} \mathcal{L}(\beta_0,\beta_1)&amp;=\prod_{i=1}^n f_{Y_i}(y_i;\beta_0,\beta_1)=\prod_{i=1}^n\exp\left(y_i(\beta_0+\beta_1x_i)-e^{\beta_0+\beta_1x_i}-\ln y_i!\right)\\ \ell(\beta_0,\beta_1)&amp;=\sum_{i=1}^n y_i(\beta_0+\beta_1x_i)-e^{\beta_0+\beta_1x_i}+\text{constante}. \end{aligned}
\]</span></p>
<p>On maximise la log-vraisemblance:</p>
<p><span class="math display">\[
\begin{aligned} \frac{\partial}{\partial\beta_0}\ell(\beta_0,\beta_1)&amp;=\sum_{i=1}^n y_i-e^{\beta_0+\beta_1x_i}\\ \frac{\partial}{\partial\beta_1}\ell(\beta_0,\beta_1)&amp;=\sum_{i=1}^n y_ix_i-x_i e^{\beta_0+\beta_1x_i}\\ \end{aligned}
\]</span></p>
<p>Donc, les équations à résoudre sont</p>
<p><span class="math display">\[
\begin{aligned} \sum_{i=1}^n y_i-e^{\beta_0+\beta_1x_i}&amp;=0\\ \sum_{i=1}^n x_i(y_i-e^{\beta_0+\beta_1x_i})&amp;=0.\\ \end{aligned}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-glm-deviance_binomiale" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-glm-deviance_binomiale"><span class="header-section-number">5.5</span> Déviance du modèle binomial</h2>
<p>Montrer que la déviance pour le modèle binomial est <span class="math display">\[
D(y,\hat{\mu})=2\sum_{i=1}^n m_i \left[y_i\ln\left(\frac{y_i}{\hat{\mu}_i}\right)+(1-y_i)\ln\left(\frac{1-y_i}{1-\hat{\mu}_i}\right)\right].
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La déviance est <span class="math display">\[
D(y;\hat{\mu})=2(\ell_n(\tilde{\theta})-\ell_n(\hat{\theta})).
\]</span></p>
<p>Pour le modèle Binomial, on a <span class="math display">\[
\begin{aligned}
\ell_n(\theta)&amp;=\sum_{i=1}^n\frac{Y_i\ln\left(\frac{\mu_i}{1-\mu_i}\right)+\ln(1-\mu_i)}{1/m_i}.
\end{aligned}
\]</span></p>
<p>Alors, dans le modèle complet, <span class="math inline">\(\mu_i=Y_i\)</span> et on trouve <span class="math display">\[
\begin{aligned}
\ell_n(\tilde{\theta})&amp;=\sum_{i=1}^n\frac{Y_i\ln\left(\frac{Y_i}{1-Y_i}\right)+\ln(1-Y_i)}{1/m_i}.
\end{aligned}
\]</span> Dans le modèle développé avec le lien log, <span class="math inline">\(\mu_i=\hat{\mu}_i\)</span> et on trouve <span class="math display">\[
\begin{aligned}
\ell_n(\hat{\theta})&amp;=\sum_{i=1}^n\frac{Y_i\ln\left(\frac{\hat{\mu}_i}{1-\hat{\mu}_i}\right)+\ln(1-\hat{\mu}_i)}{1/m_i}.
\end{aligned}
\]</span> Finalement, la déviance est <span class="math display">\[
\begin{aligned}
D(y;\hat{\mu})&amp;=\sum_{i=1}^n\frac{Y_i\ln\left(\frac{Y_i}{1-Y_i}\right)+\ln(1-Y_i)}{1/m_i}-\frac{Y_i\ln\left(\frac{\hat{\mu}_i}{1-\hat{\mu}_i}\right)+\ln(1-\hat{\mu}_i)}{1/m_i}\\
&amp;=\sum_{i=1}^n m_i\left[Y_i\ln\left(\frac{Y_i}{\hat{\mu}_i}\right)+(1-Y_i)\ln\left(\frac{1-Y_i}{1-\hat{\mu}_i}\right)\right].
\end{aligned}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-glm-residus_gamma" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-glm-residus_gamma"><span class="header-section-number">5.6</span> Résidus pour la loi gamma</h2>
<p>Trouver les expressions des résidus de Pearson, d’Anscombe et de déviance pour la loi Gamma.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pearson : <span class="math inline">\(r_{P_i} = (Y_i-\hat{\mu}_i)/\hat{\mu}_i\)</span>, Anscombe : <span class="math inline">\(r_{A_i} = (3(Y_i^{1/3}-\hat{\mu}_i^{1/3}))(\hat{\mu}_i^{1/3})\)</span>, Déviance : <span class="math inline">\(r_{D_i}=sign(Y_i-\hat{\mu}_i)\sqrt{2\left(\ln\left(\frac{\hat{\mu}_i}{Y_i}\right)+\frac{Y_i-\hat{\mu}_i}{\hat{\mu}_i}\right)}\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pour la distribution Gamma, on a <span class="math inline">\(V(t)=t^2\)</span> et <span class="math inline">\(b(t)=-\ln(-t)\)</span>.</p>
<p>Résidus de Pearson: <span class="math display">\[r_{P_i}=\frac{Y_i-\hat{\mu}_i}{\sqrt{\hat{\mu}_i^2}}=\frac{Y_i-\hat{\mu}_i}{\hat{\mu}_i}.\]</span> Résidus d’Anscombe : <span class="math display">\[
\begin{aligned}
A(t)&amp;=\int_{0}^{t} \frac{\text{d}s}{s^{2/3}}=3t^{1/3}\\
\dot{A}(t)&amp;=\frac{1}{s^{2/3}}\\
r_{A_i}&amp;=\frac{A(Y_i)-A(\hat{\mu}_i)}{\dot{A}(\hat{\mu}_i)\sqrt{V(\hat{\mu}_i)}}=\frac{3(Y_i^{1/3}-\hat{\mu}_i^{1/3})}{\hat{\mu}_i^{1/3}}.
\end{aligned}
\]</span> Résidus de déviance : <span class="math display">\[
\begin{aligned}
D_i&amp;=2\left(-\frac{Y_i}{Y_i}-\ln(Y_i)+\frac{Y_i}{\hat{\mu}_i}+\ln(\hat{\mu}_i)\right)\\
&amp;=2\left(\ln\left(\frac{\hat{\mu}_i}{Y_i}\right)+\frac{Y_i-\hat{\mu}_i}{\hat{\mu}_i}\right)\\
r_{D_i}&amp;=sign(Y_i-\hat{\mu}_i)\sqrt{2\left(\ln\left(\frac{\hat{\mu}_i}{Y_i}\right)+\frac{Y_i-\hat{\mu}_i}{\hat{\mu}_i}\right)}.
\end{aligned}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-glm-tests_resistance" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-glm-tests_resistance"><span class="header-section-number">5.7</span> Tests de résistance</h2>
<p>Les données suivantes représentent des données de comptage, du nombre d’échec pour trois appareils médicaux (M1, M2 et M3) lors de tests de résistance sur 1000 appareils de chaque type et pour quatre niveaux de résistance mécanique différents (I, II, III, IV).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;"><code>Device</code> &nbsp;<code>Stress Level</code></th>
<th style="text-align: center;"><code>I</code></th>
<th style="text-align: center;"><code>II</code></th>
<th style="text-align: center;"><code>III</code></th>
<th style="text-align: center;"><code>IV</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>M1</code></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>M2</code></td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>M3</code></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">19</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>À l’aide de la modélisation Poisson (lien canonique), évaluer s’il y a une différence significative entre les taux d’échec des appareils.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Il s’agit d’un modèle à deux facteurs, avec <code>Device</code> qui prend les trois niveaux M1, M2 et M3 et <code>Stress</code> qui prend quatre niveaux. Le niveau de base pour <code>Device</code> est M1 au <code>Stress</code> I. Une analyse de déviance permet de vérifier quels paramètres sont significatifs.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Failures <span class="sc">~</span> Level<span class="sc">*</span>Machine,<span class="at">family=</span>poisson,<span class="at">data=</span>stresstest)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(glm)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: poisson, link: log

Response: Failures

Terms added sequentially (first to last)

              Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                             11     35.844              
Level          3  20.8567         8     14.987 0.0001127 ***
Machine        2  12.2154         6      2.772 0.0022256 ** 
Level:Machine  6   2.7719         0      0.000 0.8368866    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">6</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.59159</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">2</span>)</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.991465</code></pre>
</div>
</div>
<p>Le modèle <span class="math display">\[\text{Stress+Device+Stress.Device}\]</span> est ajusté en premier. La différence de déviance par rapport au modèle plus simple <span class="math inline">\(\text{Stress+Device}\)</span> est 2.7719 sur 6 degés de liberté, ce qui n’est pas significatif par rapport au quantile <span class="math inline">\(\chi^{2}_{(6,0.95)}=12.59\)</span>. Ainsi, le modèle <span class="math inline">\(\text{Stress+Device}\)</span> est une simplification adéquate du modèle plus complexe. Si on teste la significativité des paramètres de déviance, on trouve que la différence de déviance est 12.2154 sur 2 degrés de liberté, ce qui est significatif parce que <span class="math inline">\(\chi^{2}_{(2,0.95)}=5.99\)</span>. À partir de cette analyse, on conclut qu’il y a une différence significative entre le taux d’échec et les différents appareils.</p>
</div>
</div>
</div>
</section>
<section id="sec-glm-sinistres_auto_royaume_uni" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="sec-glm-sinistres_auto_royaume_uni"><span class="header-section-number">5.8</span> Sinistres automobiles au Royaume-Uni</h2>
<p>Les données pour cet exercice sot contenues dans le fichier <code>BritishCar.csv (sep='';'')</code> disponible sur le site du cours. On y trouve les montants de réclamations moyens pour les dommages causés au véhicule du détenteur de la police pour les véhicules assurés au Royaume-Uni en 1975. Les moyennes sont en livres sterling ajustées pour l’inflation.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>OwnerAge</code></td>
<td style="text-align: left;">Âge du détenteur de la police (8 catégories)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Model</code></td>
<td style="text-align: left;">Type de voiture (4 groupes)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>CarAge</code></td>
<td style="text-align: left;">Âge du véhicule, en années (4 catégories)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>NClaims</code></td>
<td style="text-align: left;">Nombre de réclamations</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>AvCost</code></td>
<td style="text-align: left;">Coût moyen par réclamation, en livres sterling</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>On s’intéresse à la modélisation du coût moyen par réclamation.</p>
<p><strong>a)</strong> Ajuster un modèle de régression Gamma avec lien inverse pour la variable endogène <code>AvCost</code>. Inclure les effets principaux <code>OwnerAge</code>, <code>Model</code> et <code>CarAge</code>.</p>
<p><strong>b)</strong> Quelle est l’espérance du coût moyen de la réclamation pour un détenteur de police âgé entre 17 et 20 ans, avec une auto de type A âgée de moins de 3 ans ?</p>
<p><strong>c)</strong> Interpréter brièvement les coefficients pour la variable exogène <code>OwnerAge</code>.</p>
<p><strong>d)</strong> Interpréter brièvement les coefficients pour la variable exogène <code>Model</code>.</p>
<p><strong>e)</strong> Interpréter brièvement les coefficients pour la variable exogène <code>CarAge</code>.</p>
<p><strong>f)</strong> Pour quelle combinaison de variables exogènes l’espérance du coût de réclamation est-elle la plus élevée? Calculer sa valeur.</p>
<p><strong>g)</strong> Pour quelle combinaison de variables exogènes l’espérance du coût de réclamation est-elle la plus faible? Calculer sa valeur.</p>
<p><strong>h)</strong> Quelle est la déviance pour ce modèle? Est-ce que le modèle semble adéquat?</p>
<p><strong>i)</strong> Tracer le graphique des résidus de Pearson en fonction des valeurs prédites, des résidus d’Ascombe en fonction des valeurs prédites et des résidus de déviance en fonction des valeurs prédites.</p>
<p><strong>j)</strong> Obtient-on les mêmes conclusions aux sous-questions a) à h) si on utilise un lien logarithmique plutôt que le lien inverse?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> En R, on obtient</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>modinv <span class="ot">&lt;-</span> <span class="fu">glm</span>(AvCost<span class="sc">~</span>OwnerAge<span class="sc">+</span>Model<span class="sc">+</span>CarAge,<span class="at">family=</span>Gamma,<span class="at">data=</span>Bcar) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modinv) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = AvCost ~ OwnerAge + Model + CarAge, family = Gamma, 
    data = Bcar)

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    0.0033233  0.0004038   8.230 4.42e-13 ***
OwnerAge21-24  0.0006043  0.0004159   1.453  0.14908    
OwnerAge25-29  0.0003529  0.0003933   0.897  0.37163    
OwnerAge30-34  0.0011783  0.0004572   2.577  0.01130 *  
OwnerAge35-39  0.0016372  0.0004990   3.281  0.00139 ** 
OwnerAge40-49  0.0012039  0.0004592   2.622  0.01000 ** 
OwnerAge50-59  0.0010998  0.0004511   2.438  0.01638 *  
OwnerAge60+    0.0012390  0.0004619   2.682  0.00845 ** 
ModelB        -0.0002817  0.0004049  -0.696  0.48806    
ModelC        -0.0006502  0.0003906  -1.664  0.09893 .  
ModelD        -0.0018235  0.0003481  -5.239 7.96e-07 ***
CarAge10+      0.0033776  0.0004747   7.115 1.24e-10 ***
CarAge4-7      0.0003393  0.0002723   1.246  0.21539    
CarAge8-9      0.0017423  0.0003575   4.873 3.75e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.1074529)

    Null deviance: 27.841  on 122  degrees of freedom
Residual deviance: 11.511  on 109  degrees of freedom
  (5 observations deleted due to missingness)
AIC: 1400.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><strong>b)</strong> On a utilisé un lien inverse, alors <span class="math inline">\(\esp{Y_i}=\frac{1}{\eta_i}.\)</span> Puisque les variables explicatives prennent toutes leur niveau de base, on a que <span class="math inline">\(\hat{\eta}_i=\hat{\beta}_0=0.0033233\)</span> et <span class="math display">\[\widehat{\esp{Y_i}}=0.0033233^{-1}=300.91.\]</span></p>
<p><strong>c)</strong> Puisqu’on a utilisé un lien inverse, un coefficient plus élevé implique une diminution de l’espérance du coût de la réclamation, alors qu’un coefficient négatif signifie une augmentation de cette espérance. Ici on observe que les sept coefficients sont positifs, alors la catégorie d’âge ayant une espérance de coût la plus élevée est la catégorie de base, 17-20 ans. Le coût moyen semble ensuite relativement élevé pour les jeunes entre 21 et 29 ans. La catégorie d’âge avec coût de réclamation minimal est 35-39 ans, puis la moyenne semble relativement stable pour les détenteurs de police plus âgés.</p>
<p><strong>d)</strong> Les trois coefficients pour la variable modèle sont négatifs, ce qui signifie que les réclamations pour les véhicules de type A (niveau de base) sont moins élevées en moyenne que celles pour les autres types de véhicule. Les réclamations pour les véhicules du modèle D semblent particulièrement coûteuse car le coefficient est beaucoup plus grand en valeur absolue que les autres.</p>
<p><strong>e)</strong> De la même façon, on observe que d’augmenter l’âge du véhicule diminue le coût moyen des réclamations.</p>
<p><strong>f)</strong> Pour un détenteur de police entre 17 et 20 ans, avec un véhicule de type D âgé de un à 3 ans, on trouve que <span class="math display">\[\widehat{\esp{Y_i}}=\frac{1}{\hat{\beta}_0+\hat{\beta}^{MODEL}_D}=\frac{1}{0.0033233-0.0018235}=666.76.\]</span></p>
<p><strong>g)</strong> Pour un détenteur de police entre 35 et 39 ans, avec un véhicule de type A âgé de plus de 10 ans, on trouve que <span class="math display">\[\widehat{\esp{Y_i}}=\frac{1}{\hat{\beta}_0+\hat{\beta}^{OWNERAGE}_{35-39}+\hat{\beta}^{CARAGE}_{10+}}=\frac{1}{0.0033233+0.0016372+0.0033776}=119.93.\]</span></p>
<p><strong>h)</strong> La déviance <span class="math inline">\(D(y,\hat{\mu})=11.511\)</span> est donnée dans la sortie R pour la sous-question a). On a que <span class="math display">\[\frac{D(y,\hat{\mu})}{\hat{\phi}}=\frac{11.511}{0.1074529}=107.126,\]</span> ce qui est très près de <span class="math inline">\(n-p'=109\)</span>. Le modèle semble donc adéquat.</p>
<p><strong>i)</strong> Les résidus sont calculés avec les formules trouvées à la question 6. Il faut d’abord enlever les données manquantes du vecteur contenant les coûts moyens. On obtient les graphiques suivants.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-glm-uk-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-glm-uk-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="glm_files/figure-html/fig-glm-uk-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-glm-uk-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Résidus pour le GLM gamma
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-glm-uk-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-glm-uk-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="glm_files/figure-html/fig-glm-uk-2.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-glm-uk-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Résidus pour le GLM gamma
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-glm-uk-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-glm-uk-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="glm_files/figure-html/fig-glm-uk-3.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-glm-uk-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Résidus pour le GLM gamma
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>j)</strong> a. Le modèle avec le lien logarithmique est</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>modlog <span class="ot">&lt;-</span> <span class="fu">glm</span>(AvCost <span class="sc">~</span> OwnerAge<span class="sc">+</span>Model<span class="sc">+</span>CarAge,<span class="at">family=</span><span class="fu">Gamma</span>(<span class="at">link=</span>log),<span class="at">data=</span>Bcar) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modlog) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = AvCost ~ OwnerAge + Model + CarAge, family = Gamma(link = log), 
    data = Bcar)

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    5.711739   0.103835  55.008  &lt; 2e-16 ***
OwnerAge21-24 -0.108159   0.114547  -0.944   0.3471    
OwnerAge25-29  0.005223   0.113170   0.046   0.9633    
OwnerAge30-34 -0.288090   0.113170  -2.546   0.0123 *  
OwnerAge35-39 -0.331420   0.114547  -2.893   0.0046 ** 
OwnerAge40-49 -0.280775   0.113170  -2.481   0.0146 *  
OwnerAge50-59 -0.238136   0.113170  -2.104   0.0377 *  
OwnerAge60+   -0.283521   0.113170  -2.505   0.0137 *  
ModelB         0.057951   0.075447   0.768   0.4441    
ModelC         0.154588   0.076115   2.031   0.0447 *  
ModelD         0.472290   0.078497   6.017 2.43e-08 ***
CarAge10+     -0.735513   0.078497  -9.370 1.17e-15 ***
CarAge4-7     -0.111412   0.075447  -1.477   0.1426    
CarAge8-9     -0.422538   0.076115  -5.551 2.02e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0910768)

    Null deviance: 27.841  on 122  degrees of freedom
Residual deviance: 11.263  on 109  degrees of freedom
  (5 observations deleted due to missingness)
AIC: 1398

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Avec ce modèle <span class="math inline">\(\esp{Y_i}=e^{\eta_i}.\)</span> Puisque les variables explicatives prennent toutes leur niveau de base, on a que <span class="math inline">\(\hat{\eta}_i=\hat{\beta}_0=5.711739\)</span> et <span class="math display">\[\widehat{\esp{Y_i}}=e^{5.711739}=302.39.\]</span> Cela ne diffère pas beaucoup du résultat trouvé en b).</li>
</ol>
<p>c-d-e. Puisqu’on a utilisé un lien logarithmique, on a un modèle multiplicatif. Si <span class="math inline">\(e^\beta&gt;1\)</span>, alors l’espérance du coût augmente, alors que si <span class="math inline">\(e^\beta&lt;1\)</span> alors l’espérance du coût diminue. On peut donc tirer des conclusions similaires à celles en c), d) et e).</p>
<ol start="6" type="a">
<li><p>Pour un détenteur de police entre 25 et 29 ans, avec un véhicule de type D âgé de un à 3 ans, on trouve que <span class="math display">\[\widehat{\esp{Y_i}}=\exp\left(\hat{\beta}_0+\hat{\beta}^{OWNERAGE}_{25-29}+\hat{\beta}^{MODEL}_D \right)=\exp(5.711739+0.005223+0.472290)=487.48.\]</span> On note que cette valeur est beaucoup moins élevée que celle obtenue en f).</p></li>
<li><p>Pour un détenteur de police entre 35 et 39 ans, avec un véhicule de type A âgé de plus de 10 ans, on trouve que <span class="math display">\[\widehat{\esp{Y_i}}=\exp\left(\hat{\beta}_0+\hat{\beta}^{OWNERAGE}_{35-39}+\hat{\beta}^{CARAGE}_{10+}\right)=\exp(5.711739-0.331420-0.735513)=104.04.\]</span></p></li>
<li><p>La déviance <span class="math inline">\(D(y,\hat{\mu})=11.263\)</span> est donnée dans la sortie R pour la sous-question a). On a que <span class="math display">\[\frac{D(y,\hat{\mu})}{\hat{\phi}}=\frac{11.263}{0.0910768}=123.66,\]</span> ce qui est moins près de <span class="math inline">\(n-p'=109\)</span> que pour le modèle avec le lien inverse. Le modèle semble donc moins adéquat.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="sec-glm-turbines_fissurees" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="sec-glm-turbines_fissurees"><span class="header-section-number">5.9</span> Nombre de turbines fissurées</h2>
<p>On considère les données suivantes, qui contiennent le nombre <span class="math inline">\(Y_i\)</span> de turbines sur <span class="math inline">\(m_i\)</span> qui ont été fissurées après <span class="math inline">\(x_i\)</span> heures d’opération.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(m_i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">400</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1000</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1400</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1800</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2200</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2600</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3000</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">3400</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3800</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: right;">4200</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4600</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a)</strong> En utilisant un GLM binomial avec lien canonique, dériver les estimateurs des paramètres lorsque <span class="math inline">\(x_i\)</span> est traité comme une variable exogène dichotomique avec 11 niveaux, et lorsque le prédicteur linéaire pour la donnée <span class="math inline">\(i\)</span> est <span class="math display">\[\eta_i=\beta_0+\beta_i, \text{ pour } i=1,...,11,\]</span> avec la contrainte d’identifiabilité que <span class="math inline">\(\beta_1=0\)</span>.</p>
<p><strong>b)</strong> En utilisant et un GLM binomial avec lien canonique, ajuster le modèle où le prédicteur linéaire est <span class="math display">\[\eta_i=\beta_0+\beta_1 x_i, \text{ pour } i=1,...,11.\]</span> Donner les estimations des paramètres et leur écart-type.</p>
<p><strong>c)</strong> Refaire (b) en utilisant un lien probit. Donner les estimations des paramètres et leur écart-type.</p>
<p><strong>d)</strong> Refaire (b) en utilisant un lien log-log complémentaire. Donner les estimations des paramètres et leur écart-type.</p>
<p><strong>e)</strong> Comparer les prévisions (et leurs mesures d’incertitude) sous les trois modèles ajustés en (b), (c) et (d) pour une turbine qui était en opération pour 2000 heures.</p>
<p><strong>f)</strong> Tracer un graphique pour montrer si les modèles en (b), (c) et (d) ajustent bien (ou non) les données. Commenter.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Si <span class="math inline">\(x_{i}\)</span> est traité comme une variable catégorielle à 11 niveaux, le prédicteur linéaire est écrit comme <span class="math display">\[
\eta_{i}=\beta_{0}+\beta_{i} \text{,  } i=1,...,11
\]</span></p>
<p>et <span class="math inline">\(\beta_{1}=0\)</span>. La fonction de densité de la loi binomiale est</p>
<p><span class="math display">\[
f_{Y}(y_{i})=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\pi_{i}^{y_{i}}(1-\pi_{i})^{m_{i}-y_{i}},
\]</span></p>
<p>qui peut être réécrite avec la représentation de la famille exponentielle linéaire : <span class="math display">\[
f_{Y}(y_{i})=\exp\left[y_{i}\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)+m\ln(1-\pi_{i})+\ln\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\right].
\]</span></p>
<p>Ainsi, le paramètre canonique est <span class="math inline">\(\theta_{i}=\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)\)</span> et le lien canonique est le lien logit. Ainsi,</p>
<p><span class="math display">\[
\begin{aligned} \eta_{i}&amp;=\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)=\beta_{0}+\beta_{i} \\ \pi_{i}&amp;=\frac{e^{\eta_{i}}}{1+e^{\eta_{i}}}= \frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\\ \end{aligned}
\]</span></p>
<p>L’expression sous la reparamétrisation est</p>
<p><span class="math display">\[
\begin{aligned} f_{Y}(y_{i})&amp;=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\left(\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\right)^{y_{i}}\left(\frac{1}{1+e^{\beta_{0}+\beta_{i}}}\right)^{m_{i}-y_{i}}\\ &amp;=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\frac{e^{y_{i}(\beta_{0}+\beta_{i})}}{(1+e^{\beta_{0}+\beta_{i}})^{m_{i}}}\\ \end{aligned}
\]</span></p>
<p>La vraisemblance <span class="math inline">\(L\)</span> et la log-vraisemblance <span class="math inline">\(l\)</span> sont montrées ci-bas :</p>
<p><span class="math display">\[
\begin{aligned} L(\beta_{0},...,\beta_{11};y_{1},...,y_{11})&amp;=\prod_{i=1}^{11} \begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\frac{e^{y_{i}(\beta_{0}+\beta_{i})}}{(1+e^{\beta_{0}+\beta_{i}})^{m_{i}}}\\ \ell(\beta_{0},...,\beta_{11};y_{1},...,y_{11})&amp;=\sum_{i=1}^{11} \left[\ln\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}+y_{i}(\beta_{0}+\beta_{i})-m_{i}\ln(1+e^{\beta_{0}+\beta_{i}})\right]\\ \end{aligned}
\]</span></p>
<p>On a</p>
<p><span class="math display">\[
\begin{aligned} \frac{\partial \ell}{\partial \beta_{0}}&amp;=\sum_{i=1}^{11} \left[y_{i}-m_{i}\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\right]\\ \frac{\partial \ell}{\partial \beta_{i}}&amp;=y_{i}-m_{i}\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}} \text{,  } i=2,...,11,\\ \end{aligned}
\]</span></p>
<p>et <span class="math inline">\(\beta_{1}=0\)</span> par contrainte du modèle. Les estimateurs du maximum de vraisemblance pour les paramètres sont obtenus en résolvant le système d’équations <span class="math inline">\(\frac{\partial \ell}{\partial \beta_{i}}=0,\)</span> <span class="math inline">\(i=0,...,11\)</span> :</p>
<p><span class="math display">\[
\begin{aligned} \sum_{i=1}^{11} \left[y_{i}-m_{i}\frac{e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}{1+e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}\right]&amp;=0\\ y_{i}-m_{i}\frac{e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}{1+e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}&amp;=0 \text{,  } i=2,...,11,\\ \Rightarrow \hat{\beta}_{0}+\hat{\beta}_{i}=\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)&amp; \text{,  } i=2,...,11,\\ \end{aligned}
\]</span></p>
<p>En utilisant la première équation et en substituant <span class="math inline">\(\hat{\beta}_{0}+\hat{\beta}_{i}\)</span> par <span class="math inline">\(\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)\)</span>, <span class="math display">\[
\begin{aligned} &amp;y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}+\sum_{i=2}^{11} \left[y_{i}-m_{i}\frac{\left(\frac{y_{i}}{m_{i}-y_{i}}\right)}{1+\left(\frac{y_{i}}{m_{i}-y_{i}}\right)}\right]=0\\ &amp;y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}+\sum_{i=2}^{11} \left[y_{i}-m_{i}\frac{y_{i}}{m_{i}}\right]=0\\ &amp;y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}=0\\ &amp;\hat{\beta}_{0}=\ln\left(\frac{y_{1}}{m_{1}-y_{1}}\right)\\ &amp;\hat{\beta}_{i}=\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)-\hat{\beta}_{0}=\ln\left(\frac{y_{i}/(m_{i}-y_{i})}{y_{1}/(m_{1}-y_{1})}\right)  \text{,  } i=2,...,11.\\ \end{aligned}
\]</span></p>
<p>Les estimations des paramètres du modèle sont obtenues avec R :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(beta0 <span class="ot">&lt;-</span> <span class="fu">log</span>(y[<span class="dv">1</span>]<span class="sc">/</span>(m[<span class="dv">1</span>]<span class="sc">-</span>y[<span class="dv">1</span>]))) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.917771</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(beta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fu">log</span>(y[<span class="sc">-</span><span class="dv">1</span>]<span class="sc">/</span>(m[<span class="sc">-</span><span class="dv">1</span>]<span class="sc">-</span>y[<span class="sc">-</span><span class="dv">1</span>]))<span class="sc">-</span>beta0)) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0000000 0.4122448 0.6151856 0.6740261 1.3083328 1.7137979 1.6184877
 [8] 2.7636201 3.5239065 3.0178542 3.2542430</code></pre>
</div>
</div>
<p>Résultat :</p>
<p><span class="math display">\[
\hat{\beta}=(-2.9178, 0, 0.4122, 0.6152, 0.6740, 1.3083, 1.7138, 1.6185, 2.7636, 3.5239, 3.0179, 3.2542)^\top.
\]</span></p>
<p>Pour valider la cohérence des résultats, on utilise la propriété d’invariance de l’estimation par maximum de vraisemblance. On vérifie que les estimations de <span class="math inline">\(\pi_{i}\)</span> en utilisant la fonction expit sont bien <span class="math inline">\(\hat{\pi}_{i}=\frac{y_{i}}{m_{i}}\)</span> :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(pi <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta0<span class="sc">+</span>beta)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(beta0<span class="sc">+</span>beta))) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.05128205 0.07547170 0.09090909 0.09589041 0.16666667 0.23076923
 [7] 0.21428571 0.46153846 0.64705882 0.52500000 0.58333333</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>y<span class="sc">/</span>m </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.05128205 0.07547170 0.09090909 0.09589041 0.16666667 0.23076923
 [7] 0.21428571 0.46153846 0.64705882 0.52500000 0.58333333</code></pre>
</div>
</div>
<p><strong>b)</strong> Le GLM binomial avec lien logit et prédicteur linéaire <span class="math inline">\(\eta_{i}=\beta_{0}+\beta_{1}x_{i}\)</span>, <span class="math inline">\(i=1,...,11\)</span> est ajusté aux données avec R et la commande :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(<span class="fu">cbind</span>(y,m<span class="sc">-</span>y) <span class="sc">~</span> x,<span class="at">family=</span>binomial) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Les estimations des paramètres sont <span class="math inline">\(\hat{\beta}_{0}=-3.6070615\)</span> et <span class="math inline">\(\hat{\beta}_{1}=0.0009121\)</span>, avec écart-type <span class="math inline">\(SE(\hat{\beta}_{0})=0.3533875\)</span> et <span class="math inline">\(SE(\hat{\beta}_{1})=0.0001084\)</span>.</p>
<p><strong>c)</strong> Le GLM binomial avec lien probit et prédicteur linéaire <span class="math inline">\(\eta_{i}=\beta_{0}+\beta_{1}x_{i}\)</span>, <span class="math inline">\(i=1,...,11\)</span> est ajusté aux données avec R et la commande :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(<span class="fu">cbind</span>(y,m<span class="sc">-</span>y) <span class="sc">~</span> x,<span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>probit)) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Les estimations des paramètres sont <span class="math inline">\(\hat{\beta}_{0}=-2.080\)</span> et <span class="math inline">\(\hat{\beta}_{1}=5.230\times10^{-4}\)</span>, avec écart-type <span class="math inline">\(SE(\hat{\beta}_{0})=0.1852\)</span> et <span class="math inline">\(SE(\hat{\beta}_{1})=5.973\times10^{-5}\)</span>.</p>
<p><strong>d)</strong> Le GLM binomial avec lien log-log complémentaire et prédicteur linéaire <span class="math inline">\(\eta_{i}=\beta_{0}+\beta_{1}x_{i}\)</span>, <span class="math inline">\(i=1,...,11\)</span> est ajusté aux données avec R et la commande :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(<span class="fu">cbind</span>(y,m<span class="sc">-</span>y) <span class="sc">~</span> x,<span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>cloglog)) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Les estimations des paramètres sont <span class="math inline">\(\hat{\beta}_{0}=-3.360\)</span> et <span class="math inline">\(\hat{\beta}_{1}=7.480\times10^{-4}\)</span>, avec écart-type <span class="math inline">\(SE(\hat{\beta}_{0})=0.3061\)</span> et <span class="math inline">\(SE(\hat{\beta}_{1})=8.622\times10^{-5}\)</span>.</p>
<p><strong>e)</strong> Les prévisions sont obtenues avec l’inverse de la fonction de lien. Pour le modèle avec lien canonique (modèle b), on trouve <span class="math display">\[
\hat{y}_{2000}=\frac{e^{\hat{\beta}_{0}+2000\hat{\beta}_{1}}}{1+e^{\hat{\beta}_{0}+2000\hat{\beta}_{1}}}=0.1439472.
\]</span></p>
<p>De façon alternative, la commande <code>predict(modelb,data.frame(x=2000),type="response",se.fit=TRUE)</code> est utilisée pour obtenir les prévisions et leur écart-type. Les prévisions et les écarts-types sont dans le tableau suivant. La probabilité de développer des fissures après 2000 heures d’opération est de 14.39 % selon le modèle b (écart-type de 2.08%). Cela est comparable à ce qui est obtenu avec le modèle log-log complémentaire (d) pour lequel la probabilité estimée est 13.36 % avec écart-type 2.03 %. La précision est un peu meilleure avec ce modèle vu la variance plus petite. La probabilité estimée avec le modèle probit avec (c) est plus élevée à 15.06 % avec écart-type de 2.06 %.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Predictions and Standard Errors for Predictions for the 3 Models</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 23%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mesure</th>
<th style="text-align: center;">Model b (logit link)</th>
<th style="text-align: center;">Model c (probit link)</th>
<th style="text-align: center;">Model d (compl. log-log link)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\hat{y}_{2000}\)</span></td>
<td style="text-align: center;">0.1439472</td>
<td style="text-align: center;">0.1506150</td>
<td style="text-align: center;">0.1436447</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(SE(\hat{y}_{2000})\)</span></td>
<td style="text-align: center;">0.0208026</td>
<td style="text-align: center;">0.0206215</td>
<td style="text-align: center;">0.0203080</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>f)</strong> La figure <a href="#fig-glm-modfit" class="quarto-xref"><span>5.4</span></a> montre le nuage des points avec les trois modèles ajustés. On l’a obtenu avec le code R suivant, où et sont les inverses des fonctions de lien correspondantes :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y<span class="sc">/</span>m,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">xlab=</span><span class="st">"Number of Hours of Operation (x)"</span>, <span class="at">ylab=</span><span class="st">"Prob of Developing Fissures"</span>) </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">4800</span>,<span class="dv">1</span>) </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(j,<span class="fu">ilogit</span>(<span class="fu">coef</span>(modelb)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(modelb)[<span class="dv">2</span>]<span class="sc">*</span>j),<span class="at">lwd=</span><span class="dv">2</span>) <span class="fu">lines</span>(j,<span class="fu">iprobit</span>(<span class="fu">coef</span>(modelc)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(modelc)[<span class="dv">2</span>]<span class="sc">*</span>j),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>) <span class="fu">lines</span>(j,<span class="fu">icloglog</span>(<span class="fu">coef</span>(modeld)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(modeld)[<span class="dv">2</span>]<span class="sc">*</span>j),<span class="at">lty=</span><span class="dv">3</span>,<span class="at">col=</span><span class="dv">4</span>,<span class="at">lwd=</span><span class="dv">2</span>) <span class="fu">legend</span>(<span class="st">"topleft"</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Logit"</span>,<span class="st">"Probit"</span>,<span class="st">"Complementary log-log"</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),<span class="at">col=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>),<span class="at">lwd=</span><span class="fu">rep</span>(<span class="dv">2</span>,<span class="dv">3</span>)) </span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-glm-modfit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-glm-modfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="glm_files/figure-html/fig-glm-modfit-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-glm-modfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Logistic, Probit and Complementary Log-Log Model Fit
</figcaption>
</figure>
</div>
</div>
</div>
<p>Il est facile d’observer que l’ajuster est meilleur lorsque le nombre d’heures d’opération est plus petit. Il semble y avoir une variance croissante des observations avec la variable explicative. C’est attendu dans un GLM. Les trois lignes de modèles ajustés sont légèrement différentes. Le lien probit mène à une estimation plus basse dans les queues et une plus grande estimation dans le milieu du support de la variable explicative. Le modèle probit semble moins représentatif des données que les autres modèles. Le lien log-log complémentaire (d) prévoit des probabilités de fissures plus élevées dans les extrêmes. Cela semble être un meilleur ajustement pour les données, et ce, avec une variance des prévisions plus basse. La ligne du modèle avec lien canonique est entre les deux modèles. Cela pourrait être un modèle raisonnable pour les données.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapitres/selection.html" class="pagination-link" aria-label="Sélection de modèle et régression régularisée">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sélection de modèle et régression régularisée</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapitres/comptage.html" class="pagination-link" aria-label="Modélisation de données de comptage">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modélisation de données de comptage</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>