## Famille exponentielle linéaire {#sec-glm-famille_expo_lineaire}

Est-ce que les distributions suivantes font partie de la famille exponentielle linéaire? Si oui, écrire la densité sous la forme exponentielle linéaire, donner le paramètre canonique, le paramètre de dispersion, l'espérance et la variance de $Y$ en termes de la fonction $b()$ et la relation $V()$ entre la moyenne et la variance.

**a)** Normale$(\mu,\sigma^2)$

**b)** Uniforme$(0,\beta)$

**c)** Poisson$(\lambda)$

**d)** Bernoulli$(\pi)$

**e)** Binomiale$(m, \pi)$, $m>0$ est un entier et est connu (On considère $Y^*=Y/m$).

**f)** Pareto$(\alpha,\lambda)$

**g)** Gamma$(\alpha,\beta)$

**h)** Binomiale négative$(r,\pi)$ avec $r$ connu (On considère $Y^*=Y/r$).

::: {.callout-tip collapse="true" title="Solution complète"}
**a)** 

- Paramètre canonique: $\theta=\mu$

- Paramètre de dispersion: $\phi=\sigma^2$

- $b(\theta)=\frac{\theta^2}{2}$

- $\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\frac{\theta^2}{2}=\theta=\mu$

- $\var{Y}=\phi\ddot{b}(\theta)=\sigma^2\frac{\partial}{\partial\theta}\theta=\sigma^2$

- $V(\mu)=1$.

**b)**  Uniforme$(0,\beta)$: non. Le domaine dépend du paramètre $\beta$.

**c)**  Poisson$(\lambda)$ :
$$
\begin{aligned}
f_{Y}(y;\lambda)&=\frac{\lambda^{y}e^{-\lambda}}{y!} \text{, pour }y\in \mathbb{N}^{+}\\
&=\exp\{y\ln \lambda - \lambda - \ln y!\}\\
f_{Y}(y;\theta,\phi)&=\exp\left\{\frac{y\theta - e^{\theta}}{\phi} - \ln y!\right\}.
\end{aligned}
$$
- Paramètre canonique: $\theta=\ln \lambda$

- Paramètre de dispersion: $\phi=1$

- $b(\theta)=e^{\theta}$

- $\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}e^{\theta}=e^{\theta}=\lambda$

- $\var{Y}=\phi\ddot{b}(\theta)=\frac{\partial}{\partial\theta}e^{\theta}=e^{\theta}=\lambda$

- $V(\mu)=\mu$.

**d)**  Bernoulli$(\pi)$
$$
\begin{aligned}
f_{Y}(y;\pi)&=\pi^{y}(1-\pi)^{1-y}1(y \in \{0,1\})\\
&=\exp\left\{y\ln\left(\frac{\pi}{1-\pi}\right)+\ln(1-\pi)\right\}1(y \in \{0,1\}).\\
\end{aligned}
$$
- Paramètre canonique: $\theta=\ln\left(\frac{\pi}{1-\pi}\right)$

- Paramètre de dispersion:  $\phi=1$

- $b(\theta)=\ln(1+e^{\theta})$

- $\esp{Y}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\ln(1+e^{\theta})=\frac{e^{\theta}}{1+e^\theta}=\pi$

- $\var{Y}=\phi\ddot{b}(\theta)=\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1+e^\theta}=\frac{e^\theta}{(1+e^\theta)^2}=\pi(1-\pi)$

- $V(\mu)=\mu(1-\mu)$.

**e)** Binomiale$(m, \pi)$, $m>0$ est un entier et est connu.
$$
\begin{aligned}
f_{Y}(y;\pi)&=\begin{pmatrix} m\\y\end{pmatrix}\pi^{y}(1-\pi)^{m-y}1(y \in \{0,1,...,m\})\\
&=\exp\left\{y\ln\left(\frac{\pi}{1-\pi}\right)+m\ln(1-\pi)+\ln\begin{pmatrix} m\\y\end{pmatrix}\right\}1(y \in \{0,1,...,m\}).\\
\end{aligned}
$$
Dans cette représentation, on a $$\esp{Y}=m\pi \text{ et } \var{Y}=m\pi(1-\pi).$$ Cette forme est moins utilisée car l'espérance de $Y$ dépend de $m$, le paramètre de dispersion. Souvent, on transforme les données. On utilise plutôt $Y^{*}=Y/m$. Alors, pour ces données transformées,
$$
\begin{aligned}
f_{Y^{*}}(y;\pi)&=\exp\left\{my\ln\left(\frac{\pi}{1-\pi}\right)+m\ln(1-\pi)+\ln\begin{pmatrix} m\\my\end{pmatrix}\right\},  y \in \{0,1/m,...,1\}\\
&=\exp\left\{\frac{y\ln\left(\frac{\pi}{1-\pi}\right)+\ln(1-\pi)}{1/m}+\ln\begin{pmatrix} m\\my\end{pmatrix}\right\},  y \in \{0,1/m,...,1\}.\\
\end{aligned}
$$
- Paramètre canonique : $\theta=\ln\left(\frac{\pi}{1-\pi}\right)$

- Paramètre de dispersion:  $\phi=1/m$

- $b(\theta)=\ln(1+e^{\theta})$

- $\esp{Y^*}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}\ln(1+e^{\theta})=\frac{e^{\theta}}{1+e^\theta}=\pi$

- $\var{Y^*}=\phi\ddot{b}(\theta)=\frac{1}{m}\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1+e^\theta}=\frac{e^\theta}{m(1+e^\theta)^2}=\frac{\pi(1-\pi)}{m}$

- $V(\mu)=\mu(1-\mu)$.

**f)** Pareto$(\alpha,\lambda)$: non.

**g)** Gamma$(\alpha,\beta)$
Soit $Y\sim Gamma(\alpha,\beta)$. Alors, avec un peu de travail, la densité peut être écrite sous la forme exponentielle linéaire.

$$
f_{Y}(y;\alpha,\beta)=\frac{\beta^{\alpha}}{\Gamma(\alpha)}y^{\alpha-1}e^{-\beta y},
$$ pour $y>0$. On reparamétrise: $\mu=\alpha/\beta=\esp{Y}$ et $\alpha$, on a donc $\beta=\alpha/\mu$ et 

$$
f_{Y}(y;\alpha,\mu)=\frac{1}{y\Gamma(\alpha)}\left(\frac{\alpha y}{\mu}\right)^{\alpha}\exp\left\{-\frac{\alpha y}{\mu}\right\}.
$$ 

Posons $\theta=-1/\mu$, et $a(\phi)=1/\alpha$, alors on trouve 

$$
f_{Y}(y;\theta,\phi)=\exp\left\{\frac{y\theta +\ln(-\theta)}{\phi} +\alpha\ln\alpha+(\alpha-1)\ln y -\ln\Gamma(\alpha)\right\}.
$$ 

Donc, $b(\theta)=-\ln(-\theta)$ et $a(\phi)=1/\alpha \Rightarrow \dot{b}(\theta)=\frac{-1}{\theta}=\mu$ et $\ddot{b}(\theta)=\frac{1}{\theta^{2}}=\mu^{2}$. Finalement, 
$$
\esp{Y}=\frac{-1}{\theta}=\mu \text{ et } \var{Y}=\frac{1}{\alpha}\mu^{2}.
$$

**h)** Binomiale négative$(r,\pi)$ avec $r$ connu. On considère $Y^*=Y/r$:
$$
\begin{aligned}
f_Y^*(y)&=\begin{pmatrix} r+ry-1\\ry\end{pmatrix}\pi^r(1-\pi)^{ry}, \text{ pour } y\in \{0,\frac{1}{r},\frac{2}{r},...\}\\
&=\exp\left(ry\ln(1-\pi)+r\ln\pi+\ln\begin{pmatrix} r+ry-1\\ry\end{pmatrix}\right).
\end{aligned}
$$
- Paramètre canonique: $\theta=\ln(1-\pi)$

- Paramètre de dispersion:  $\phi=1/r$

- $b(\theta)=-\ln(1-e^\theta)$

- $\esp{Y^*}=\dot{b}(\theta)=\frac{\partial}{\partial\theta}-\ln(1-e^\theta)=\frac{e^{\theta}}{1-e^\theta}=\frac{1-\pi}{\pi}$

- $\var{Y^*}=\phi\ddot{b}(\theta)=\frac{1}{r}\frac{\partial}{\partial\theta}\frac{e^{\theta}}{1-e^\theta}=\frac{e^\theta}{r(1-e^\theta)^2}=\frac{(1-\pi)}{r\pi^2}$

- $V(\mu)=\mu(\mu+1)$.
:::

