## Nombre de turbines fissurées {#sec-glm-turbines_fissurees}

```{r echo}
#| echo: false

x <- c(400, seq(from = 1000, to = 4600, by = 400))
m <- c(39, 53, 33, 73, 30, 39, 42, 13, 34, 40, 36)
y <- c(2, 4, 3, 7, 5, 9, 9, 6, 22, 21, 21)
```

On considère les données suivantes, qui contiennent le nombre $Y_i$ de turbines sur $m_i$ qui ont été fissurées après $x_i$ heures d'opération.

\begin{center}
\begin{tabular}{rrr}
\hline
$x_i$ &$m_i$ & $Y_i$\\\hline
400& 39 &2\\
1000& 53 &4\\
1400 &33& 3\\
1800& 73 &7\\
2200 &30& 5\\
2600& 39 &9\\
3000 &42& 9\\
3400& 13 &6\\
3800 &34& 22\\
4200& 40 &21\\
4600 &36& 21\\\hline
\end{tabular}
\end{center}

**a)** En utilisant un GLM binomial avec lien canonique, dériver les estimateurs des paramètres lorsque $x_i$ est traité comme une variable exogène dichotomique avec 11 niveaux, et lorsque le prédicteur linéaire pour la donnée $i$ est $$\eta_i=\beta_0+\beta_i, \text{ pour } i=1,...,11,$$ avec la contrainte d'identifiabilité que $\beta_1=0$.

**b)** En utilisant \textsf{R} et un GLM binomial avec lien canonique, ajuster le modèle où le prédicteur linéaire est $$\eta_i=\beta_0+\beta_1 x_i, \text{ pour } i=1,...,11.$$ Donner les estimations des paramètres et leur écart-type.

**c)** Refaire (b) en utilisant un lien probit. Donner les estimations des paramètres et leur écart-type.

**d)** Refaire (b) en utilisant un lien log-log complémentaire. Donner les estimations des paramètres et leur écart-type.

**e)** Comparer les prévisions (et leurs mesures d'incertitude) sous les trois modèles ajustés en (b), (c) et (d) pour une turbine qui était en opération pour 2000 heures.

**f)** Tracer un graphique pour montrer si les modèles en (b), (c) et (d) ajustent bien (ou non) les données. Commenter.

::: {.callout-tip collapse="true" title="Solution complète"}
**a)** If $x_{i}$ is treated as a factor predictor with 11 levels, the linear predictor is written as $$\eta_{i}=\beta_{0}+\beta_{i} \text{,  } i=1,...,11$$ and $\beta_{1}=0$. The binomial density is the following: $$f_{Y}(y_{i})=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\pi_{i}^{y_{i}}(1-\pi_{i})^{m_{i}-y_{i}},$$ which can be rewritten in a exponential family representation as: $$f_{Y}(y_{i})=\exp\left[y_{i}\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)+m\ln(1-\pi_{i})+\ln\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\right].$$ Hence, the canonical parameter is $\theta_{i}=\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)$ and the canonical link is the logit link. Thus, $$
\begin{aligned} \eta_{i}&=\ln\left(\frac{\pi_{i}}{1-\pi_{i}}\right)=\beta_{0}+\beta_{i} \\ \pi_{i}&=\frac{e^{\eta_{i}}}{1+e^{\eta_{i}}}= \frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\\ \end{aligned}
$$ The expression of the density in the reparametrization is then $$
\begin{aligned} f_{Y}(y_{i})&=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\left(\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\right)^{y_{i}}\left(\frac{1}{1+e^{\beta_{0}+\beta_{i}}}\right)^{m_{i}-y_{i}}\\ &=\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\frac{e^{y_{i}(\beta_{0}+\beta_{i})}}{(1+e^{\beta_{0}+\beta_{i}})^{m_{i}}}\\ \end{aligned}
$$ The likelihood $L$ and the log-likelihood $l$ are shown below: $$
\begin{aligned} L(\beta_{0},...,\beta_{11};y_{1},...,y_{11})&=\prod_{i=1}^{11} \begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}\frac{e^{y_{i}(\beta_{0}+\beta_{i})}}{(1+e^{\beta_{0}+\beta_{i}})^{m_{i}}}\\ \ell(\beta_{0},...,\beta_{11};y_{1},...,y_{11})&=\sum_{i=1}^{11} \left[\ln\begin{pmatrix} m_{i} \\ y_{i} \end{pmatrix}+y_{i}(\beta_{0}+\beta_{i})-m_{i}\ln(1+e^{\beta_{0}+\beta_{i}})\right]\\ \end{aligned}
$$ We have $$
\begin{aligned} \frac{\partial \ell}{\partial \beta_{0}}&=\sum_{i=1}^{11} \left[y_{i}-m_{i}\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}}\right]\\ \frac{\partial \ell}{\partial \beta_{i}}&=y_{i}-m_{i}\frac{e^{\beta_{0}+\beta_{i}}}{1+e^{\beta_{0}+\beta_{i}}} \text{,  } i=2,...,11,\\ \end{aligned}
$$ and $\beta_{1}=0$ by constraint of the model. The maximum likelihood estimators for the parameters are derived by solving the system of equations $\frac{\partial \ell}{\partial \beta_{i}}=0,$ $i=0,...,11$: $$
\begin{aligned} \sum_{i=1}^{11} \left[y_{i}-m_{i}\frac{e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}{1+e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}\right]&=0\\ y_{i}-m_{i}\frac{e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}{1+e^{\hat{\beta}_{0}+\hat{\beta}_{i}}}&=0 \text{,  } i=2,...,11,\\ \Rightarrow \hat{\beta}_{0}+\hat{\beta}_{i}=\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)& \text{,  } i=2,...,11,\\ \end{aligned}
$$  Using the first equation and replacing $\hat{\beta}_{0}+\hat{\beta}_{i}$ by $\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)$, $$
\begin{aligned} &y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}+\sum_{i=2}^{11} \left[y_{i}-m_{i}\frac{\left(\frac{y_{i}}{m_{i}-y_{i}}\right)}{1+\left(\frac{y_{i}}{m_{i}-y_{i}}\right)}\right]=0\\ &y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}+\sum_{i=2}^{11} \left[y_{i}-m_{i}\frac{y_{i}}{m_{i}}\right]=0\\ &y_{1}-m_{1}\frac{e^{\hat{\beta}_{0}}}{1+e^{\hat{\beta}_{0}}}=0\\ &\hat{\beta}_{0}=\ln\left(\frac{y_{1}}{m_{1}-y_{1}}\right)\\ &\hat{\beta}_{i}=\ln\left(\frac{y_{i}}{m_{i}-y_{i}}\right)-\hat{\beta}_{0}=\ln\left(\frac{y_{i}/(m_{i}-y_{i})}{y_{1}/(m_{1}-y_{1})}\right)  \text{,  } i=2,...,11.\\ \end{aligned}
$$ The estimates of the model parameters are easily found in \textsf{R} as follows: ```{r} (beta0 <- log(y[1]/(m[1]-y[1]))) (beta <- c(0,log(y[-1]/(m[-1]-y[-1]))-beta0)) ``` Hence, here $$\hat{\beta}=(-2.9178, 0, 0.4122, 0.6152, 0.6740, 1.3083, 1.7138, 1.6185, 2.7636, 3.5239, 3.0179, 3.2542)^\top.$$ As a consistency check following from the invariance property of maximum likelihood estimation, we can verify that the estimates of $\pi_{i}$ using the expit function are equal to the MLE estimates $\hat{\pi}_{i}=\frac{y_{i}}{m_{i}}$: ```{r} (pi <- exp(beta0+beta)/(1+exp(beta0+beta))) y/m ```

**b)** The Binomial GLM model with logit link and the linear predictor $\eta_{i}=\beta_{0}+\beta_{1}x_{i}$, $i=1,...,11$ is fitted to the data using \textsf{R} and the command: ```{r echo} #| eval: false glm(cbind(y,m-y) x,family=binomial) ``` The estimates of the parameters are $\hat{\beta}_{0}=-3.6070615$ and $\hat{\beta}_{1}=0.0009121$, with standard error $SE(\hat{\beta}_{0})=0.3533875$ and $SE(\hat{\beta}_{1})=0.0001084$.

**c)** The Binomial GLM model with probit link and the linear predictor $\eta_{i}=\beta_{0}+\beta_{1}x_{i}$, $i=1,...,11$ is fitted to the data using \textsf{R} and the command: ```{r echo} #| eval: false glm(cbind(y,m-y) x,family=binomial(link=probit)) ``` The estimates of the parameters are $\hat{\beta}_{0}=-2.080$ and $\hat{\beta}_{1}=5.230\times10^{-4}$, with standard error $SE(\hat{\beta}_{0})=0.1852$ and $SE(\hat{\beta}_{1})=5.973\times10^{-5}$.

**d)** The Binomial GLM model with complementary log-log link and the linear predictor $\eta_{i}=\beta_{0}+\beta_{1}x_{i}$, $i=1,...,11$ is fitted to the data using \textsf{R} and the command: ```{r echo} #| eval: false glm(cbind(y,m-y) x,family=binomial(link=cloglog)) ``` The estimates of the parameters are $\hat{\beta}_{0}=-3.360$ and $\hat{\beta}_{1}=7.480\times10^{-4}$, with standard error $SE(\hat{\beta}_{0})=0.3061$ and $SE(\hat{\beta}_{1})=8.622\times10^{-5}$.

**e)** Predictions can be found using the inverse of the link function. For the model with canonical link (model from b), we find that $$\hat{y}_{2000}=\frac{e^{\hat{\beta}_{0}+2000\hat{\beta}_{1}}}{1+e^{\hat{\beta}_{0}+2000\hat{\beta}_{1}}}=0.1439472.$$ Alternatively, the command \texttt{predict(modelb,data.frame(x=2000),type="response",se.fit=TRUE)} can be used to calculate the predictions and associated standard errors. The resulting predictions and standard errors are presented in Table @sec-glm-turbines_fissurees. The probability of developing fissures after 2000 hours of operations is 14.39\

**f)** Figure @sec-glm-turbines_fissurees shows a plot of the data points along with the three fitted lines. It was obtained using the following code in \textsf{R}, where \texttt{ilogit, iprobit} and \texttt{icloglog} are the inverse of the corresponding link functions: ```{r echo} #| eval: false plot(x,y/m,pch=19,xlab="Number of Hours of Operation (x)", ylab="Prob of Developing Fissures") j <- seq(0,4800,1) lines(j,ilogit(coef(modelb)[1]+coef(modelb)[2]*j),lwd=2) lines(j,iprobit(coef(modelc)[1]+coef(modelc)[2]*j),lty=2,col=2,lwd=2) lines(j,icloglog(coef(modeld)[1]+coef(modeld)[2]*j),lty=3,col=4,lwd=2) legend("topleft",legend=c("Logit","Probit","Complementary log-log"), lty=c(1,2,3),col=c(1,2,4),lwd=rep(2,3)) ``` ```{r echo} #| echo: false modelb <- glm(cbind(y,m-y) x,family=binomial) modelc <- glm(cbind(y,m-y) x,family=binomial(link=probit)) modeld <- glm(cbind(y,m-y) x,family=binomial(link=cloglog)) ilogit <- function(x) exp(x)/(1+exp(x)) iprobit <- function(x) pnorm(x) icloglog <- function(x) 1 - exp(-exp(x)) ```
:::

