## Consommation d'essence avec régression linéaire multiple {#sec-multiple-carburant_multiple}

Répéter l'exercice @simple.@sec-simple-consommation_carburant en
  ajoutant la cylindrée du véhicule en litres dans le modèle. La
  cylindrée est exprimée en pouces cubes dans les données.  Or, 1
  pouce correspond à 2,54 cm et un litre est définit comme étant
  1 $\text{dm}^3$, soit \nombre{1000} $\text{cm}^3$. Trouver un
  intervalle de confiance pour la consommation en carburant d'une
  voiture de \nombre{1350} kg ayant un moteur de 1,8 litre.
```{r echo}
#| echo: false

carburant <- read.table("data/carburant.dat", header = TRUE)
consommation <- 235.1954/carburant$mpg
poids <- carburant$poids * 0.45455 * 1000
cylindree <- carburant$cylindree * 2.54^3/1000
fit <- lm(consommation   poids + cylindree)
b <- coef(fit)
s <- summary(fit)$sigma
R2 <- summary(fit)$r.squared
f <- summary(fit)$fstatistic[1]
pred.pi <- predict(fit, newdata = data.frame(poids = 1350, cylindree = 1.8),
                   interval = "prediction")
```

::: {.callout-note collapse="true" title="Éléments de réponse"}
\stepcounter{enumi}

**a)** $R^2 = \Sexpr{format(signif(R2, 4), dec = ",")}$ et $F = \Sexpr{format(signif(f, 4), dec = ",")}$

**b)** $\Sexpr{format(signif(pred.pi[1], 4), dec = ",")} \pm \Sexpr{format(signif(diff(pred.pi[c(1, 3)]), 3), dec = ",")}$
:::

::: {.callout-tip collapse="true" title="Solution complète"}
**a)** On importe les données dans \textsf{R}, puis on effectue les conversions nécessaires. Comme précédemment, la variable \texttt{consommation} contient la consommation des voitures en $\ell$/100 km et la variable \texttt{poids} le poids en kilogrammes. On ajoute la variable \texttt{cylindree}, qui contient la cylindrée des voitures en litres. ```{r echo} #| eval: false carburant <- read.table("carburant.dat", header = TRUE) consommation <- 235.1954/carburant$mpg poids <- carburant$poids * 0.45455 * 1000 cylindree <- carburant$cylindree * 2.54^3/1000 ```

**b)** La fonction \texttt{summary} fournit l'information essentielle pour juger de la validité et de la qualité du modèle: ```{r} fit <- lm(consommation   poids + cylindree) summary(fit) ``` Le modèle est donc le suivant: $$ Y_i = \Sexpr{format(signif(b[1], 4), dec = ",")} + \Sexpr{format(signif(b[2], 4), dec = ",")} x_{i1} + \Sexpr{format(signif(b[3], 4), dec = ",")} x_{i2} + \varepsilon_i, \quad \epsvec_i \sim \Norm(0, \Sexpr{format(signif(s, 4), dec = ",")}^2 \mat{I}) $$ où $Y_i$ est la consommation en litres aux 100 kilomètres, $x_{i1}$ le poids en kilogrammes et $x_{i2}$ la cylindrée en litres. Le faible seuil observé du test $F$ indique une régression globalement très significative. Les tests $t$ des paramètres individuels indiquent également que les deux variables du modèle sont significatives. Enfin, le $R^2$ de 

**c)** On veut calculer un intervalle de confiance pour la consommation prévue d'une voiture de \nombre{1350} kg ayant un moteur d'une cylindrée de 1,8 litres. On obtient, avec la fonction \texttt{predict}: ```{r} predict(fit, newdata = data.frame(poids = 1350, cylindree = 1.8), interval = "prediction") ```
:::

