## Inclusion d'une donnée aberrante {#sec-multiple-outlier}

La base de données `OutlierExample.csv` disponible sur le site du cours contient 19 observations de base, et trois observations supplémentaires, notées par les `CODES` 1, 2 et 3, qui sont aberrantes ou influentes.

**a)** Importez la base de données et tracez un nuage de points de `Y` en fonction de `x`.

**b)** Roulez les lignes de code suivantes pour observer le graphique avec les 3 points ajoutés 

```{text} 
library(ggplot2) 
ggplot(dat, aes(x= X, y= Y, label=CODES))+ geom_point() + geom_text(aes(label=ifelse(CODES>0,CODES,'')),hjust=0,vjust=0) 
```

**c)** Ajustez un modèle linéaire en incluant seulement les 19 points dont le code est 0. Regardez l'ajustement et commentez.

**d)** Ajustez un modèle linéaire en incluant les 19 points dont le code est 0 et le point de code 1. Quel est l'effet de l'inclusion de ce point sur le $R^2$ et sur les estimations des paramètres? Étudiez le résultat de la fonction `influence.measures()`.

**e)** Ajustez un modèle linéaire en incluant les 19 points dont le code est 0 et le point de code 2. Quel est l'effet de l'inclusion de ce point sur le $R^2$ et sur les estimations des paramètres? Étudiez le résultat de la fonction `influence.measures()`.

**f)** Ajustez un modèle linéaire en incluant les 19 points dont le code est 0 et le point de code 3. Quel est l'effet de l'inclusion de ce point sur le $R^2$ et sur les estimations des paramètres? Étudiez le résultat de la fonction `influence.measures()`.

::: {.callout-tip collapse="true" title="Solution complète"}
On pourrait croire qu'un point sur 20, ça ne change rien, mais ce n'est pas le cas! Le point 1 a un effet sur la pente et la qualité de l'ajustement. Le point 2 a un grand levier mais n'affecte pas beaucoup les estimations, le point 3 a un grand levier et un gros effet. Pour observer l'effet, exécuter le code R suivant.

```{r}
#| eval: false


dat <- read.csv("OutlierExample.csv")

dim(dat)

summary(dat)

library(ggplot2)

ggplot(dat, aes(x= X, y= Y, label=CODES))+
  geom_point() +
  geom_text(aes(label=ifelse(CODES>0,CODES,'')),hjust=0,vjust=0)

fit0 <- lm(Y ~ X,dat,subset=(CODES==0))
summary(fit0)
plot(dat[,1:2],pch=16)
points(dat[match(1:3,dat$CODES),1:2],col=2:4,pch=16:18,cex=1.2)
abline(fit0)

fit1 <- lm(Y ~ X,dat,subset=(CODES<=1))
summary(fit1)
abline(fit1,col=2,lty=2)

fit2 <- lm(Y ~ X,dat,subset=(CODES%in%c(0,2)))
summary(fit2)
abline(fit2,col=3,lty=3)

fit3 <- lm(Y ~ X,dat,subset=(CODES%in%c(0,3)))
summary(fit3)
abline(fit3,col=4,lty=4)

influence.measures(fit0)
influence.measures(fit1)
influence.measures(fit2)
influence.measures(fit3)
```
:::

