## Contribution des joueurs étoiles de la NBA {#sec-binom-contributions_etoiles_nba}

Jones \& Parker (2010)\footnote{M.L. Jones et R.J. Parker, (2010) *Chance*: $\mathbf{23}, 29-15$} ont écrit un article sur les contributions des joueurs étoiles de la NBA. Entre autres, ils ont donné des équations de prévision pour la probabilité $\pi$ de victoire pour un match de LeBron James dans la saison 2008-2009. Les variables exogènes sont:
\begin{description}
\item[$x_1$:] Points produits par centaine de possessions (note offensive).
\item[$x_2$:] Points donnés par centaine de possessions (note défensive), plus petit signifie "meilleur" dans ce cas.
\item[$x_3$:] Vaut 1 si la partie est discutée à domicile (0 sinon).
\end{description}
Les coefficients estimés sont $$\hat{\beta}_0=1.379, \quad   \hat{\beta}_1=0.119,\quad   \hat{\beta}_2=-0.139,\quad \text{ et}\quad   \hat{\beta}_3=3.393.$$

**a)** On a utilisé un lien logistique. Écrire l'équation de la probabilité estimée $\hat{\pi}$ en fonction des paramètres du modèle.

**b)** Calculer la probabilité de gain lorsque la note défensive de LeBron James est égale à sa médiane pour la saison, i.e., $x_2=99.5$, que la note offensive est à son $75^{e}$ centile, $x_1=136.1$ et que $x_3=0$. Refaire avec le $25^e$ centile $x_1=108.7$, comparer et interpréter.

**c)** Quel est l'impact de la variable $x_3$? Utiliser les médianes $x_1=123.2$ et $x_2=99.5$.

::: {.callout-tip collapse="true" title="Solution complète"}
**a)**  $$ \mathrm{logit}(\hat{\pi})=1.379+0.119x_1-0.139x_2+3.393x_3 \Rightarrow \hat{\pi}=\frac{\exp(1.379+0.119x_1-0.139x_2+3.393x_3)}{1+\exp(1.379+0.119x_1-0.139x_2+3.393x_3)} $$

**b)** Au $75^e$ centile, on a $$\hat{\pi}=\frac{\exp(1.379+0.119\times 136.1-0.139\times 99.5)}{1+\exp(1.379+0.119\times 136.1-0.139\times 99.5)}=97.68\

**c)** À l'étranger, on a $$ \hat{\pi}=\frac{\exp(1.379+0.119\times 123.2-0.139\times 99.5)}{1+\exp(1.379+0.119\times 123.2-0.139\times 99.5)}=90.1\
:::

